/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeviceDetail,
  DeviceSummary,
  ErrorBody,
  JournalPage,
  JournalParams
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listResponse200 = {
  data: DeviceSummary[]
  status: 200
}

export type listResponse401 = {
  data: void
  status: 401
}

export type listResponse403 = {
  data: void
  status: 403
}

export type listResponseSuccess = (listResponse200) & {
  headers: Headers;
};
export type listResponseError = (listResponse401 | listResponse403) & {
  headers: Headers;
};

export type listResponse = (listResponseSuccess | listResponseError)

export const getListUrl = () => {




  return `/api/devices`
}

/**
 * @summary GET /api/devices (viewer+) — the fleet, ordered by device id.
 */
export const list = async ( options?: RequestInit): Promise<listResponse> => {

  const res = await fetch(getListUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listResponse
}





export const getListQueryKey = () => {
    return [
    `/api/devices`
    ] as const;
    }


export const getListQueryOptions = <TData = Awaited<ReturnType<typeof list>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof list>>> = ({ signal }) => list({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListQueryResult = NonNullable<Awaited<ReturnType<typeof list>>>
export type ListQueryError = void


export function useList<TData = Awaited<ReturnType<typeof list>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof list>>,
          TError,
          Awaited<ReturnType<typeof list>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useList<TData = Awaited<ReturnType<typeof list>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/devices (viewer+) — the fleet, ordered by device id.
 */

export function useList<TData = Awaited<ReturnType<typeof list>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof list>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type detailResponse200 = {
  data: DeviceDetail
  status: 200
}

export type detailResponse401 = {
  data: void
  status: 401
}

export type detailResponse403 = {
  data: void
  status: 403
}

export type detailResponse404 = {
  data: ErrorBody
  status: 404
}

export type detailResponseSuccess = (detailResponse200) & {
  headers: Headers;
};
export type detailResponseError = (detailResponse401 | detailResponse403 | detailResponse404) & {
  headers: Headers;
};

export type detailResponse = (detailResponseSuccess | detailResponseError)

export const getDetailUrl = (deviceId: string,) => {




  return `/api/devices/${deviceId}`
}

/**
 * @summary GET /api/devices/{device_id} (viewer+) — one device, with render
provenance.
 */
export const detail = async (deviceId: string, options?: RequestInit): Promise<detailResponse> => {

  const res = await fetch(getDetailUrl(deviceId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: detailResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as detailResponse
}





export const getDetailQueryKey = (deviceId: string,) => {
    return [
    `/api/devices/${deviceId}`
    ] as const;
    }


export const getDetailQueryOptions = <TData = Awaited<ReturnType<typeof detail>>, TError = void | ErrorBody>(deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetailQueryKey(deviceId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof detail>>> = ({ signal }) => detail(deviceId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: deviceId !== null && deviceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetailQueryResult = NonNullable<Awaited<ReturnType<typeof detail>>>
export type DetailQueryError = void | ErrorBody


export function useDetail<TData = Awaited<ReturnType<typeof detail>>, TError = void | ErrorBody>(
 deviceId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail>>,
          TError,
          Awaited<ReturnType<typeof detail>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetail<TData = Awaited<ReturnType<typeof detail>>, TError = void | ErrorBody>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detail>>,
          TError,
          Awaited<ReturnType<typeof detail>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetail<TData = Awaited<ReturnType<typeof detail>>, TError = void | ErrorBody>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/devices/{device_id} (viewer+) — one device, with render
provenance.
 */

export function useDetail<TData = Awaited<ReturnType<typeof detail>>, TError = void | ErrorBody>(
 deviceId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detail>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetailQueryOptions(deviceId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type journalResponse200 = {
  data: JournalPage
  status: 200
}

export type journalResponse401 = {
  data: void
  status: 401
}

export type journalResponse403 = {
  data: void
  status: 403
}

export type journalResponse404 = {
  data: ErrorBody
  status: 404
}

export type journalResponseSuccess = (journalResponse200) & {
  headers: Headers;
};
export type journalResponseError = (journalResponse401 | journalResponse403 | journalResponse404) & {
  headers: Headers;
};

export type journalResponse = (journalResponseSuccess | journalResponseError)

export const getJournalUrl = (deviceId: string,
    params?: JournalParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/devices/${deviceId}/journal?${stringifiedParams}` : `/api/devices/${deviceId}/journal`
}

/**
 * @summary GET /api/devices/{device_id}/journal (viewer+) — status journal
page, newest first (§7.3 forensic record; late-backfilled records
appear in seq order, not arrival order).
 */
export const journal = async (deviceId: string,
    params?: JournalParams, options?: RequestInit): Promise<journalResponse> => {

  const res = await fetch(getJournalUrl(deviceId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: journalResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as journalResponse
}





export const getJournalQueryKey = (deviceId: string,
    params?: JournalParams,) => {
    return [
    `/api/devices/${deviceId}/journal`, ...(params ? [params] : [])
    ] as const;
    }


export const getJournalQueryOptions = <TData = Awaited<ReturnType<typeof journal>>, TError = void | ErrorBody>(deviceId: string,
    params?: JournalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof journal>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getJournalQueryKey(deviceId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof journal>>> = ({ signal }) => journal(deviceId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: deviceId !== null && deviceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof journal>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type JournalQueryResult = NonNullable<Awaited<ReturnType<typeof journal>>>
export type JournalQueryError = void | ErrorBody


export function useJournal<TData = Awaited<ReturnType<typeof journal>>, TError = void | ErrorBody>(
 deviceId: string,
    params: undefined |  JournalParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof journal>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof journal>>,
          TError,
          Awaited<ReturnType<typeof journal>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJournal<TData = Awaited<ReturnType<typeof journal>>, TError = void | ErrorBody>(
 deviceId: string,
    params?: JournalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof journal>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof journal>>,
          TError,
          Awaited<ReturnType<typeof journal>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useJournal<TData = Awaited<ReturnType<typeof journal>>, TError = void | ErrorBody>(
 deviceId: string,
    params?: JournalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof journal>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/devices/{device_id}/journal (viewer+) — status journal
page, newest first (§7.3 forensic record; late-backfilled records
appear in seq order, not arrival order).
 */

export function useJournal<TData = Awaited<ReturnType<typeof journal>>, TError = void | ErrorBody>(
 deviceId: string,
    params?: JournalParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof journal>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getJournalQueryOptions(deviceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






