/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  DeployRequest,
  DeployResponse,
  ErrorBody
} from '../../model';





export type deployResponse200 = {
  data: DeployResponse
  status: 200
}

export type deployResponse401 = {
  data: void
  status: 401
}

export type deployResponse403 = {
  data: ErrorBody
  status: 403
}

export type deployResponse422 = {
  data: ErrorBody
  status: 422
}

export type deployResponseSuccess = (deployResponse200) & {
  headers: Headers;
};
export type deployResponseError = (deployResponse401 | deployResponse403 | deployResponse422) & {
  headers: Headers;
};

export type deployResponse = (deployResponseSuccess | deployResponseError)

export const getDeployUrl = () => {




  return `/api/deploy`
}

/**
 * @summary POST /api/deploy (operator+) — deploy a stack to a scope (§11.4).
Authors `app.yaml` (package ref + `enabled:true` + profile) into the
scope's layer(s) via the tree authoring path; re-renders affected
devices.
 */
export const deploy = async (deployRequest: DeployRequest, options?: RequestInit): Promise<deployResponse> => {

  const res = await fetch(getDeployUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deployRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deployResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deployResponse
}





export const getDeployMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deploy>>, TError,{data: DeployRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deploy>>, TError,{data: DeployRequest}, TContext> => {

const mutationKey = ['deploy'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deploy>>, {data: DeployRequest}> = (props) => {
          const {data} = props ?? {};

          return  deploy(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeployMutationResult = NonNullable<Awaited<ReturnType<typeof deploy>>>
    export type DeployMutationBody = DeployRequest
    export type DeployMutationError = void | ErrorBody

    /**
 * @summary POST /api/deploy (operator+) — deploy a stack to a scope (§11.4).
Authors `app.yaml` (package ref + `enabled:true` + profile) into the
scope's layer(s) via the tree authoring path; re-renders affected
devices.
 */
export const useDeploy = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deploy>>, TError,{data: DeployRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deploy>>,
        TError,
        {data: DeployRequest},
        TContext
      > => {
      return useMutation(getDeployMutationOptions(options), queryClient);
    }
    export type undeployResponse200 = {
  data: DeployResponse
  status: 200
}

export type undeployResponse401 = {
  data: void
  status: 401
}

export type undeployResponse403 = {
  data: ErrorBody
  status: 403
}

export type undeployResponse422 = {
  data: ErrorBody
  status: 422
}

export type undeployResponseSuccess = (undeployResponse200) & {
  headers: Headers;
};
export type undeployResponseError = (undeployResponse401 | undeployResponse403 | undeployResponse422) & {
  headers: Headers;
};

export type undeployResponse = (undeployResponseSuccess | undeployResponseError)

export const getUndeployUrl = () => {




  return `/api/undeploy`
}

/**
 * @summary POST /api/undeploy (operator+) — remove a stack from a scope (§11.4:
"the same call removing the app from the scope"). Removes the app dir
from the scope's layer(s); re-renders affected devices.
 */
export const undeploy = async (deployRequest: DeployRequest, options?: RequestInit): Promise<undeployResponse> => {

  const res = await fetch(getUndeployUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deployRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: undeployResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as undeployResponse
}





export const getUndeployMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undeploy>>, TError,{data: DeployRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof undeploy>>, TError,{data: DeployRequest}, TContext> => {

const mutationKey = ['undeploy'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof undeploy>>, {data: DeployRequest}> = (props) => {
          const {data} = props ?? {};

          return  undeploy(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UndeployMutationResult = NonNullable<Awaited<ReturnType<typeof undeploy>>>
    export type UndeployMutationBody = DeployRequest
    export type UndeployMutationError = void | ErrorBody

    /**
 * @summary POST /api/undeploy (operator+) — remove a stack from a scope (§11.4:
"the same call removing the app from the scope"). Removes the app dir
from the scope's layer(s); re-renders affected devices.
 */
export const useUndeploy = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undeploy>>, TError,{data: DeployRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof undeploy>>,
        TError,
        {data: DeployRequest},
        TContext
      > => {
      return useMutation(getUndeployMutationOptions(options), queryClient);
    }
