/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  BlameEntry,
  CommitResponse,
  DiffEntry,
  ErrorBody,
  ListRevisionsParams,
  PutFilesRequest,
  RenderKickResponse,
  RevisionDetail,
  RevisionInfo
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type renderKickResponse200 = {
  data: RenderKickResponse
  status: 200
}

export type renderKickResponse401 = {
  data: void
  status: 401
}

export type renderKickResponse403 = {
  data: void
  status: 403
}

export type renderKickResponseSuccess = (renderKickResponse200) & {
  headers: Headers;
};
export type renderKickResponseError = (renderKickResponse401 | renderKickResponse403) & {
  headers: Headers;
};

export type renderKickResponse = (renderKickResponseSuccess | renderKickResponseError)

export const getRenderKickUrl = () => {




  return `/api/render`
}

/**
 * @summary POST /api/render — operator+ manual kick: re-render every device at
the current local head (C4). No-change devices are not bumped (D3).
 */
export const renderKick = async ( options?: RequestInit): Promise<renderKickResponse> => {

  const res = await fetch(getRenderKickUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: renderKickResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as renderKickResponse
}





export const getRenderKickMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renderKick>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof renderKick>>, TError,void, TContext> => {

const mutationKey = ['renderKick'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof renderKick>>, void> = () => {


          return  renderKick(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RenderKickMutationResult = NonNullable<Awaited<ReturnType<typeof renderKick>>>

    export type RenderKickMutationError = void

    /**
 * @summary POST /api/render — operator+ manual kick: re-render every device at
the current local head (C4). No-change devices are not bumped (D3).
 */
export const useRenderKick = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof renderKick>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof renderKick>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getRenderKickMutationOptions(options), queryClient);
    }
    export type blameResponse200 = {
  data: BlameEntry[]
  status: 200
}

export type blameResponse401 = {
  data: void
  status: 401
}

export type blameResponse403 = {
  data: void
  status: 403
}

export type blameResponseSuccess = (blameResponse200) & {
  headers: Headers;
};
export type blameResponseError = (blameResponse401 | blameResponse403) & {
  headers: Headers;
};

export type blameResponse = (blameResponseSuccess | blameResponseError)

export const getBlameUrl = (path: string,) => {




  return `/api/tree/blame/${path}`
}

/**
 * @summary GET /api/tree/blame/{*path} — every revision at which the path
changed, ascending (blame = SELECT, D13). `digest: null` marks a
removal.
 */
export const blame = async (path: string, options?: RequestInit): Promise<blameResponse> => {

  const res = await fetch(getBlameUrl(path),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: blameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as blameResponse
}





export const getBlameQueryKey = (path: string,) => {
    return [
    `/api/tree/blame/${path}`
    ] as const;
    }


export const getBlameQueryOptions = <TData = Awaited<ReturnType<typeof blame>>, TError = void>(path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blame>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getBlameQueryKey(path);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof blame>>> = ({ signal }) => blame(path, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: path !== null && path !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof blame>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type BlameQueryResult = NonNullable<Awaited<ReturnType<typeof blame>>>
export type BlameQueryError = void


export function useBlame<TData = Awaited<ReturnType<typeof blame>>, TError = void>(
 path: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof blame>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof blame>>,
          TError,
          Awaited<ReturnType<typeof blame>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlame<TData = Awaited<ReturnType<typeof blame>>, TError = void>(
 path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blame>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof blame>>,
          TError,
          Awaited<ReturnType<typeof blame>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useBlame<TData = Awaited<ReturnType<typeof blame>>, TError = void>(
 path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blame>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/tree/blame/{*path} — every revision at which the path
changed, ascending (blame = SELECT, D13). `digest: null` marks a
removal.
 */

export function useBlame<TData = Awaited<ReturnType<typeof blame>>, TError = void>(
 path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof blame>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getBlameQueryOptions(path,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type diffResponse200 = {
  data: DiffEntry[]
  status: 200
}

export type diffResponse401 = {
  data: void
  status: 401
}

export type diffResponse403 = {
  data: void
  status: 403
}

export type diffResponse404 = {
  data: ErrorBody
  status: 404
}

export type diffResponseSuccess = (diffResponse200) & {
  headers: Headers;
};
export type diffResponseError = (diffResponse401 | diffResponse403 | diffResponse404) & {
  headers: Headers;
};

export type diffResponse = (diffResponseSuccess | diffResponseError)

export const getDiffUrl = (a: number,
    b: number,) => {




  return `/api/tree/diff/${a}/${b}`
}

/**
 * @summary GET /api/tree/diff/{a}/{b} — manifest diff between two revisions,
computed on read (D13).
 */
export const diff = async (a: number,
    b: number, options?: RequestInit): Promise<diffResponse> => {

  const res = await fetch(getDiffUrl(a,b),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: diffResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as diffResponse
}





export const getDiffQueryKey = (a: number,
    b: number,) => {
    return [
    `/api/tree/diff/${a}/${b}`
    ] as const;
    }


export const getDiffQueryOptions = <TData = Awaited<ReturnType<typeof diff>>, TError = void | ErrorBody>(a: number,
    b: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diff>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDiffQueryKey(a,b);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof diff>>> = ({ signal }) => diff(a,b, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: a !== null && a !== undefined && b !== null && b !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof diff>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DiffQueryResult = NonNullable<Awaited<ReturnType<typeof diff>>>
export type DiffQueryError = void | ErrorBody


export function useDiff<TData = Awaited<ReturnType<typeof diff>>, TError = void | ErrorBody>(
 a: number,
    b: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof diff>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof diff>>,
          TError,
          Awaited<ReturnType<typeof diff>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiff<TData = Awaited<ReturnType<typeof diff>>, TError = void | ErrorBody>(
 a: number,
    b: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diff>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof diff>>,
          TError,
          Awaited<ReturnType<typeof diff>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDiff<TData = Awaited<ReturnType<typeof diff>>, TError = void | ErrorBody>(
 a: number,
    b: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diff>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/tree/diff/{a}/{b} — manifest diff between two revisions,
computed on read (D13).
 */

export function useDiff<TData = Awaited<ReturnType<typeof diff>>, TError = void | ErrorBody>(
 a: number,
    b: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof diff>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDiffQueryOptions(a,b,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putLayerResponse200 = {
  data: CommitResponse
  status: 200
}

export type putLayerResponse401 = {
  data: void
  status: 401
}

export type putLayerResponse403 = {
  data: ErrorBody
  status: 403
}

export type putLayerResponse422 = {
  data: ErrorBody
  status: 422
}

export type putLayerResponseSuccess = (putLayerResponse200) & {
  headers: Headers;
};
export type putLayerResponseError = (putLayerResponse401 | putLayerResponse403 | putLayerResponse422) & {
  headers: Headers;
};

export type putLayerResponse = (putLayerResponseSuccess | putLayerResponseError)

export const getPutLayerUrl = (layer: string,) => {




  return `/api/tree/layers/${layer}`
}

/**
 * @summary PUT /api/tree/layers/{layer} — apply one layer's complete content
(D14 batch semantics: the body IS the layer; a file absent from the
body is removed). Identical content => no new revision.
 */
export const putLayer = async (layer: string,
    putFilesRequest: PutFilesRequest, options?: RequestInit): Promise<putLayerResponse> => {

  const res = await fetch(getPutLayerUrl(layer),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putFilesRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putLayerResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putLayerResponse
}





export const getPutLayerMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLayer>>, TError,{layer: string;data: PutFilesRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putLayer>>, TError,{layer: string;data: PutFilesRequest}, TContext> => {

const mutationKey = ['putLayer'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putLayer>>, {layer: string;data: PutFilesRequest}> = (props) => {
          const {layer,data} = props ?? {};

          return  putLayer(layer,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutLayerMutationResult = NonNullable<Awaited<ReturnType<typeof putLayer>>>
    export type PutLayerMutationBody = PutFilesRequest
    export type PutLayerMutationError = void | ErrorBody

    /**
 * @summary PUT /api/tree/layers/{layer} — apply one layer's complete content
(D14 batch semantics: the body IS the layer; a file absent from the
body is removed). Identical content => no new revision.
 */
export const usePutLayer = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putLayer>>, TError,{layer: string;data: PutFilesRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putLayer>>,
        TError,
        {layer: string;data: PutFilesRequest},
        TContext
      > => {
      return useMutation(getPutLayerMutationOptions(options), queryClient);
    }
    export type putPackageResponse200 = {
  data: CommitResponse
  status: 200
}

export type putPackageResponse401 = {
  data: void
  status: 401
}

export type putPackageResponse403 = {
  data: ErrorBody
  status: 403
}

export type putPackageResponse422 = {
  data: ErrorBody
  status: 422
}

export type putPackageResponseSuccess = (putPackageResponse200) & {
  headers: Headers;
};
export type putPackageResponseError = (putPackageResponse401 | putPackageResponse403 | putPackageResponse422) & {
  headers: Headers;
};

export type putPackageResponse = (putPackageResponseSuccess | putPackageResponseError)

export const getPutPackageUrl = (name: string,
    version: string,) => {




  return `/api/tree/packages/${name}/${version}`
}

/**
 * @summary PUT /api/tree/packages/{name}/{version} — vendor a margo package
directory into the tree (D11: packages are vendored in v1, keeping
render pure). The upload is validated by the margo-package crate
BEFORE anything is committed: invalid packages produce 422 and no
revision.
 */
export const putPackage = async (name: string,
    version: string,
    putFilesRequest: PutFilesRequest, options?: RequestInit): Promise<putPackageResponse> => {

  const res = await fetch(getPutPackageUrl(name,version),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putFilesRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putPackageResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putPackageResponse
}





export const getPutPackageMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPackage>>, TError,{name: string;version: string;data: PutFilesRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putPackage>>, TError,{name: string;version: string;data: PutFilesRequest}, TContext> => {

const mutationKey = ['putPackage'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putPackage>>, {name: string;version: string;data: PutFilesRequest}> = (props) => {
          const {name,version,data} = props ?? {};

          return  putPackage(name,version,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutPackageMutationResult = NonNullable<Awaited<ReturnType<typeof putPackage>>>
    export type PutPackageMutationBody = PutFilesRequest
    export type PutPackageMutationError = void | ErrorBody

    /**
 * @summary PUT /api/tree/packages/{name}/{version} — vendor a margo package
directory into the tree (D11: packages are vendored in v1, keeping
render pure). The upload is validated by the margo-package crate
BEFORE anything is committed: invalid packages produce 422 and no
revision.
 */
export const usePutPackage = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putPackage>>, TError,{name: string;version: string;data: PutFilesRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putPackage>>,
        TError,
        {name: string;version: string;data: PutFilesRequest},
        TContext
      > => {
      return useMutation(getPutPackageMutationOptions(options), queryClient);
    }
    export type listRevisionsResponse200 = {
  data: RevisionInfo[]
  status: 200
}

export type listRevisionsResponse401 = {
  data: void
  status: 401
}

export type listRevisionsResponse403 = {
  data: void
  status: 403
}

export type listRevisionsResponseSuccess = (listRevisionsResponse200) & {
  headers: Headers;
};
export type listRevisionsResponseError = (listRevisionsResponse401 | listRevisionsResponse403) & {
  headers: Headers;
};

export type listRevisionsResponse = (listRevisionsResponseSuccess | listRevisionsResponseError)

export const getListRevisionsUrl = (params?: ListRevisionsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/tree/revisions?${stringifiedParams}` : `/api/tree/revisions`
}

/**
 * @summary GET /api/tree/revisions[?limit=N] — revision history, both streams,
newest first.
 */
export const listRevisions = async (params?: ListRevisionsParams, options?: RequestInit): Promise<listRevisionsResponse> => {

  const res = await fetch(getListRevisionsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listRevisionsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listRevisionsResponse
}





export const getListRevisionsQueryKey = (params?: ListRevisionsParams,) => {
    return [
    `/api/tree/revisions`, ...(params ? [params] : [])
    ] as const;
    }


export const getListRevisionsQueryOptions = <TData = Awaited<ReturnType<typeof listRevisions>>, TError = void>(params?: ListRevisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRevisions>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRevisionsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRevisions>>> = ({ signal }) => listRevisions(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRevisions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRevisionsQueryResult = NonNullable<Awaited<ReturnType<typeof listRevisions>>>
export type ListRevisionsQueryError = void


export function useListRevisions<TData = Awaited<ReturnType<typeof listRevisions>>, TError = void>(
 params: undefined |  ListRevisionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRevisions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRevisions>>,
          TError,
          Awaited<ReturnType<typeof listRevisions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRevisions<TData = Awaited<ReturnType<typeof listRevisions>>, TError = void>(
 params?: ListRevisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRevisions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRevisions>>,
          TError,
          Awaited<ReturnType<typeof listRevisions>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRevisions<TData = Awaited<ReturnType<typeof listRevisions>>, TError = void>(
 params?: ListRevisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRevisions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/tree/revisions[?limit=N] — revision history, both streams,
newest first.
 */

export function useListRevisions<TData = Awaited<ReturnType<typeof listRevisions>>, TError = void>(
 params?: ListRevisionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRevisions>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRevisionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type getRevisionResponse200 = {
  data: RevisionDetail
  status: 200
}

export type getRevisionResponse401 = {
  data: void
  status: 401
}

export type getRevisionResponse403 = {
  data: void
  status: 403
}

export type getRevisionResponse404 = {
  data: ErrorBody
  status: 404
}

export type getRevisionResponseSuccess = (getRevisionResponse200) & {
  headers: Headers;
};
export type getRevisionResponseError = (getRevisionResponse401 | getRevisionResponse403 | getRevisionResponse404) & {
  headers: Headers;
};

export type getRevisionResponse = (getRevisionResponseSuccess | getRevisionResponseError)

export const getGetRevisionUrl = (id: number,) => {




  return `/api/tree/revisions/${id}`
}

/**
 * @summary GET /api/tree/revisions/{id} — metadata + full manifest
(path -> blob digest) at that revision.
 */
export const getRevision = async (id: number, options?: RequestInit): Promise<getRevisionResponse> => {

  const res = await fetch(getGetRevisionUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getRevisionResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getRevisionResponse
}





export const getGetRevisionQueryKey = (id: number,) => {
    return [
    `/api/tree/revisions/${id}`
    ] as const;
    }


export const getGetRevisionQueryOptions = <TData = Awaited<ReturnType<typeof getRevision>>, TError = void | ErrorBody>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevision>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRevisionQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRevision>>> = ({ signal }) => getRevision(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRevision>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRevisionQueryResult = NonNullable<Awaited<ReturnType<typeof getRevision>>>
export type GetRevisionQueryError = void | ErrorBody


export function useGetRevision<TData = Awaited<ReturnType<typeof getRevision>>, TError = void | ErrorBody>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevision>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevision>>,
          TError,
          Awaited<ReturnType<typeof getRevision>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevision<TData = Awaited<ReturnType<typeof getRevision>>, TError = void | ErrorBody>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevision>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRevision>>,
          TError,
          Awaited<ReturnType<typeof getRevision>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRevision<TData = Awaited<ReturnType<typeof getRevision>>, TError = void | ErrorBody>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevision>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/tree/revisions/{id} — metadata + full manifest
(path -> blob digest) at that revision.
 */

export function useGetRevision<TData = Awaited<ReturnType<typeof getRevision>>, TError = void | ErrorBody>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRevision>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRevisionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type fileAtResponse200 = {
  data: Blob
  status: 200
}

export type fileAtResponse401 = {
  data: void
  status: 401
}

export type fileAtResponse403 = {
  data: void
  status: 403
}

export type fileAtResponse404 = {
  data: ErrorBody
  status: 404
}

export type fileAtResponseSuccess = (fileAtResponse200) & {
  headers: Headers;
};
export type fileAtResponseError = (fileAtResponse401 | fileAtResponse403 | fileAtResponse404) & {
  headers: Headers;
};

export type fileAtResponse = (fileAtResponseSuccess | fileAtResponseError)

export const getFileAtUrl = (id: number,
    path: string,) => {




  return `/api/tree/revisions/${id}/files/${path}`
}

/**
 * @summary GET /api/tree/revisions/{id}/files/{*path} — raw file content at a
revision.
 */
export const fileAt = async (id: number,
    path: string, options?: RequestInit): Promise<fileAtResponse> => {

  const res = await fetch(getFileAtUrl(id,path),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.blob();
  const data: fileAtResponse['data'] = body as fileAtResponse['data']
  return { data, status: res.status, headers: res.headers } as fileAtResponse
}





export const getFileAtQueryKey = (id: number,
    path: string,) => {
    return [
    `/api/tree/revisions/${id}/files/${path}`
    ] as const;
    }


export const getFileAtQueryOptions = <TData = Awaited<ReturnType<typeof fileAt>>, TError = void | ErrorBody>(id: number,
    path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fileAt>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFileAtQueryKey(id,path);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof fileAt>>> = ({ signal }) => fileAt(id,path, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined && path !== null && path !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof fileAt>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FileAtQueryResult = NonNullable<Awaited<ReturnType<typeof fileAt>>>
export type FileAtQueryError = void | ErrorBody


export function useFileAt<TData = Awaited<ReturnType<typeof fileAt>>, TError = void | ErrorBody>(
 id: number,
    path: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof fileAt>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof fileAt>>,
          TError,
          Awaited<ReturnType<typeof fileAt>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFileAt<TData = Awaited<ReturnType<typeof fileAt>>, TError = void | ErrorBody>(
 id: number,
    path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fileAt>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof fileAt>>,
          TError,
          Awaited<ReturnType<typeof fileAt>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFileAt<TData = Awaited<ReturnType<typeof fileAt>>, TError = void | ErrorBody>(
 id: number,
    path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fileAt>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/tree/revisions/{id}/files/{*path} — raw file content at a
revision.
 */

export function useFileAt<TData = Awaited<ReturnType<typeof fileAt>>, TError = void | ErrorBody>(
 id: number,
    path: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof fileAt>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFileAtQueryOptions(id,path,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






