/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateJoinTokenRequest,
  CreatedJoinToken,
  ErrorBody,
  JoinTokenInfo
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type indexResponse200 = {
  data: JoinTokenInfo[]
  status: 200
}

export type indexResponse401 = {
  data: void
  status: 401
}

export type indexResponse403 = {
  data: void
  status: 403
}

export type indexResponseSuccess = (indexResponse200) & {
  headers: Headers;
};
export type indexResponseError = (indexResponse401 | indexResponse403) & {
  headers: Headers;
};

export type indexResponse = (indexResponseSuccess | indexResponseError)

export const getIndexUrl = () => {




  return `/api/join-tokens`
}

/**
 * @summary GET /api/join-tokens (admin/operator) — hashes and metadata only.
 */
export const index = async ( options?: RequestInit): Promise<indexResponse> => {

  const res = await fetch(getIndexUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: indexResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as indexResponse
}





export const getIndexQueryKey = () => {
    return [
    `/api/join-tokens`
    ] as const;
    }


export const getIndexQueryOptions = <TData = Awaited<ReturnType<typeof index>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof index>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getIndexQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof index>>> = ({ signal }) => index({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof index>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type IndexQueryResult = NonNullable<Awaited<ReturnType<typeof index>>>
export type IndexQueryError = void


export function useIndex<TData = Awaited<ReturnType<typeof index>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof index>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof index>>,
          TError,
          Awaited<ReturnType<typeof index>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useIndex<TData = Awaited<ReturnType<typeof index>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof index>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof index>>,
          TError,
          Awaited<ReturnType<typeof index>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useIndex<TData = Awaited<ReturnType<typeof index>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof index>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/join-tokens (admin/operator) — hashes and metadata only.
 */

export function useIndex<TData = Awaited<ReturnType<typeof index>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof index>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getIndexQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createResponse201 = {
  data: CreatedJoinToken
  status: 201
}

export type createResponse401 = {
  data: void
  status: 401
}

export type createResponse403 = {
  data: void
  status: 403
}

export type createResponse404 = {
  data: ErrorBody
  status: 404
}

export type createResponse422 = {
  data: ErrorBody
  status: 422
}

export type createResponseSuccess = (createResponse201) & {
  headers: Headers;
};
export type createResponseError = (createResponse401 | createResponse403 | createResponse404 | createResponse422) & {
  headers: Headers;
};

export type createResponse = (createResponseSuccess | createResponseError)

export const getCreateUrl = () => {




  return `/api/join-tokens`
}

/**
 * @summary POST /api/join-tokens (admin/operator, D4). Returns the raw token —
shown exactly once.
 */
export const create = async (createJoinTokenRequest: CreateJoinTokenRequest, options?: RequestInit): Promise<createResponse> => {

  const res = await fetch(getCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createJoinTokenRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createResponse
}





export const getCreateMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateJoinTokenRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateJoinTokenRequest}, TContext> => {

const mutationKey = ['create'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof create>>, {data: CreateJoinTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  create(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateMutationResult = NonNullable<Awaited<ReturnType<typeof create>>>
    export type CreateMutationBody = CreateJoinTokenRequest
    export type CreateMutationError = void | ErrorBody

    /**
 * @summary POST /api/join-tokens (admin/operator, D4). Returns the raw token —
shown exactly once.
 */
export const useCreate = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof create>>, TError,{data: CreateJoinTokenRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof create>>,
        TError,
        {data: CreateJoinTokenRequest},
        TContext
      > => {
      return useMutation(getCreateMutationOptions(options), queryClient);
    }
    export type _deleteResponse204 = {
  data: void
  status: 204
}

export type _deleteResponse401 = {
  data: void
  status: 401
}

export type _deleteResponse403 = {
  data: void
  status: 403
}

export type _deleteResponseSuccess = (_deleteResponse204) & {
  headers: Headers;
};
export type _deleteResponseError = (_deleteResponse401 | _deleteResponse403) & {
  headers: Headers;
};

export type _deleteResponse = (_deleteResponseSuccess | _deleteResponseError)

export const getDeleteUrl = (tokenHash: string,) => {




  return `/api/join-tokens/${tokenHash}`
}

/**
 * @summary DELETE /api/join-tokens/{token_hash} (admin/operator) — revoke.
Idempotent: unknown or already-revoked is still 204.
 */
export const _delete = async (tokenHash: string, options?: RequestInit): Promise<_deleteResponse> => {

  const res = await fetch(getDeleteUrl(tokenHash),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: _deleteResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as _deleteResponse
}





export const getDeleteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{tokenHash: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{tokenHash: string}, TContext> => {

const mutationKey = ['_delete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof _delete>>, {tokenHash: string}> = (props) => {
          const {tokenHash} = props ?? {};

          return  _delete(tokenHash,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type _DeleteMutationResult = NonNullable<Awaited<ReturnType<typeof _delete>>>

    export type _DeleteMutationError = void

    /**
 * @summary DELETE /api/join-tokens/{token_hash} (admin/operator) — revoke.
Idempotent: unknown or already-revoked is still 204.
 */
export const useDelete = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof _delete>>, TError,{tokenHash: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof _delete>>,
        TError,
        {tokenHash: string},
        TContext
      > => {
      return useMutation(getDeleteMutationOptions(options), queryClient);
    }
