/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DurabilityStatusResponse
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type durabilityStatusResponse200 = {
  data: DurabilityStatusResponse
  status: 200
}

export type durabilityStatusResponse401 = {
  data: void
  status: 401
}

export type durabilityStatusResponse403 = {
  data: void
  status: 403
}

export type durabilityStatusResponseSuccess = (durabilityStatusResponse200) & {
  headers: Headers;
};
export type durabilityStatusResponseError = (durabilityStatusResponse401 | durabilityStatusResponse403) & {
  headers: Headers;
};

export type durabilityStatusResponse = (durabilityStatusResponseSuccess | durabilityStatusResponseError)

export const getDurabilityStatusUrl = () => {




  return `/api/durability/status`
}

/**
 * @summary GET /api/durability/status — the §9.4 API surface (viewer+; the UI
renders "last verified restore" and the degraded flag from this).
 */
export const durabilityStatus = async ( options?: RequestInit): Promise<durabilityStatusResponse> => {

  const res = await fetch(getDurabilityStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: durabilityStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as durabilityStatusResponse
}





export const getDurabilityStatusQueryKey = () => {
    return [
    `/api/durability/status`
    ] as const;
    }


export const getDurabilityStatusQueryOptions = <TData = Awaited<ReturnType<typeof durabilityStatus>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof durabilityStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDurabilityStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof durabilityStatus>>> = ({ signal }) => durabilityStatus({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof durabilityStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DurabilityStatusQueryResult = NonNullable<Awaited<ReturnType<typeof durabilityStatus>>>
export type DurabilityStatusQueryError = void


export function useDurabilityStatus<TData = Awaited<ReturnType<typeof durabilityStatus>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof durabilityStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof durabilityStatus>>,
          TError,
          Awaited<ReturnType<typeof durabilityStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDurabilityStatus<TData = Awaited<ReturnType<typeof durabilityStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof durabilityStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof durabilityStatus>>,
          TError,
          Awaited<ReturnType<typeof durabilityStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDurabilityStatus<TData = Awaited<ReturnType<typeof durabilityStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof durabilityStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/durability/status — the §9.4 API surface (viewer+; the UI
renders "last verified restore" and the degraded flag from this).
 */

export function useDurabilityStatus<TData = Awaited<ReturnType<typeof durabilityStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof durabilityStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDurabilityStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






