/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  HealthzResponse,
  ServerInfo
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type serverInfoResponse200 = {
  data: ServerInfo
  status: 200
}

export type serverInfoResponse401 = {
  data: void
  status: 401
}

export type serverInfoResponse403 = {
  data: void
  status: 403
}

export type serverInfoResponseSuccess = (serverInfoResponse200) & {
  headers: Headers;
};
export type serverInfoResponseError = (serverInfoResponse401 | serverInfoResponse403) & {
  headers: Headers;
};

export type serverInfoResponse = (serverInfoResponseSuccess | serverInfoResponseError)

export const getServerInfoUrl = () => {




  return `/api/server`
}

/**
 * @summary GET /api/server — server version + compiled-in extension
advertisement + declared tier for the ops UI. Human (session) leg of
the device-auth'd /api/reeve/v1/capabilities; viewer+.
 */
export const serverInfo = async ( options?: RequestInit): Promise<serverInfoResponse> => {

  const res = await fetch(getServerInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: serverInfoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as serverInfoResponse
}





export const getServerInfoQueryKey = () => {
    return [
    `/api/server`
    ] as const;
    }


export const getServerInfoQueryOptions = <TData = Awaited<ReturnType<typeof serverInfo>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverInfo>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getServerInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof serverInfo>>> = ({ signal }) => serverInfo({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof serverInfo>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ServerInfoQueryResult = NonNullable<Awaited<ReturnType<typeof serverInfo>>>
export type ServerInfoQueryError = void


export function useServerInfo<TData = Awaited<ReturnType<typeof serverInfo>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverInfo>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof serverInfo>>,
          TError,
          Awaited<ReturnType<typeof serverInfo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServerInfo<TData = Awaited<ReturnType<typeof serverInfo>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverInfo>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof serverInfo>>,
          TError,
          Awaited<ReturnType<typeof serverInfo>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useServerInfo<TData = Awaited<ReturnType<typeof serverInfo>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverInfo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/server — server version + compiled-in extension
advertisement + declared tier for the ops UI. Human (session) leg of
the device-auth'd /api/reeve/v1/capabilities; viewer+.
 */

export function useServerInfo<TData = Awaited<ReturnType<typeof serverInfo>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof serverInfo>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getServerInfoQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type healthzResponse200 = {
  data: HealthzResponse
  status: 200
}

export type healthzResponseSuccess = (healthzResponse200) & {
  headers: Headers;
};
;

export type healthzResponse = (healthzResponseSuccess)

export const getHealthzUrl = () => {




  return `/healthz`
}

/**
 * @summary GET /healthz — liveness (operational contract, CLAUDE.md). No auth.
 */
export const healthz = async ( options?: RequestInit): Promise<healthzResponse> => {

  const res = await fetch(getHealthzUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: healthzResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as healthzResponse
}





export const getHealthzQueryKey = () => {
    return [
    `/healthz`
    ] as const;
    }


export const getHealthzQueryOptions = <TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthzQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthz>>> = ({ signal }) => healthz({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HealthzQueryResult = NonNullable<Awaited<ReturnType<typeof healthz>>>
export type HealthzQueryError = unknown


export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof healthz>>,
          TError,
          Awaited<ReturnType<typeof healthz>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /healthz — liveness (operational contract, CLAUDE.md). No auth.
 */

export function useHealthz<TData = Awaited<ReturnType<typeof healthz>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof healthz>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHealthzQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






