/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  PutSecretRequest,
  SecretDeleted,
  SecretWritten,
  SecretsList
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listSecretsResponse200 = {
  data: SecretsList
  status: 200
}

export type listSecretsResponse401 = {
  data: void
  status: 401
}

export type listSecretsResponse403 = {
  data: void
  status: 403
}

export type listSecretsResponseSuccess = (listSecretsResponse200) & {
  headers: Headers;
};
export type listSecretsResponseError = (listSecretsResponse401 | listSecretsResponse403) & {
  headers: Headers;
};

export type listSecretsResponse = (listSecretsResponseSuccess | listSecretsResponseError)

export const getListSecretsUrl = () => {




  return `/api/secrets`
}

/**
 * @summary GET /api/secrets (viewer+): METADATA ONLY — name, scope, version,
created/rotated. Values are never readable through any route, by
anyone (§12.2 write-only after entry).
 */
export const listSecrets = async ( options?: RequestInit): Promise<listSecretsResponse> => {

  const res = await fetch(getListSecretsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listSecretsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listSecretsResponse
}





export const getListSecretsQueryKey = () => {
    return [
    `/api/secrets`
    ] as const;
    }


export const getListSecretsQueryOptions = <TData = Awaited<ReturnType<typeof listSecrets>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListSecretsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listSecrets>>> = ({ signal }) => listSecrets({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListSecretsQueryResult = NonNullable<Awaited<ReturnType<typeof listSecrets>>>
export type ListSecretsQueryError = void


export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSecrets>>,
          TError,
          Awaited<ReturnType<typeof listSecrets>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listSecrets>>,
          TError,
          Awaited<ReturnType<typeof listSecrets>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/secrets (viewer+): METADATA ONLY — name, scope, version,
created/rotated. Values are never readable through any route, by
anyone (§12.2 write-only after entry).
 */

export function useListSecrets<TData = Awaited<ReturnType<typeof listSecrets>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listSecrets>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListSecretsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type putRouteResponse200 = {
  data: SecretWritten
  status: 200
}

export type putRouteResponse401 = {
  data: void
  status: 401
}

export type putRouteResponse403 = {
  data: void
  status: 403
}

export type putRouteResponse422 = {
  data: ErrorBody
  status: 422
}

export type putRouteResponseSuccess = (putRouteResponse200) & {
  headers: Headers;
};
export type putRouteResponseError = (putRouteResponse401 | putRouteResponse403 | putRouteResponse422) & {
  headers: Headers;
};

export type putRouteResponse = (putRouteResponseSuccess | putRouteResponseError)

export const getPutRouteUrl = () => {




  return `/api/secrets`
}

/**
 * @summary PUT /api/secrets (operator+; §12.2 write-only). Set or rotate:
an existing (name, scope) gets a version bump. Kicks a render pass
so affected devices' manifests pick up the new secrets_version
(§12.4 propagation).
 */
export const putRoute = async (putSecretRequest: PutSecretRequest, options?: RequestInit): Promise<putRouteResponse> => {

  const res = await fetch(getPutRouteUrl(),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(putSecretRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: putRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as putRouteResponse
}





export const getPutRouteMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putRoute>>, TError,{data: PutSecretRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof putRoute>>, TError,{data: PutSecretRequest}, TContext> => {

const mutationKey = ['putRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putRoute>>, {data: PutSecretRequest}> = (props) => {
          const {data} = props ?? {};

          return  putRoute(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutRouteMutationResult = NonNullable<Awaited<ReturnType<typeof putRoute>>>
    export type PutRouteMutationBody = PutSecretRequest
    export type PutRouteMutationError = void | ErrorBody

    /**
 * @summary PUT /api/secrets (operator+; §12.2 write-only). Set or rotate:
an existing (name, scope) gets a version bump. Kicks a render pass
so affected devices' manifests pick up the new secrets_version
(§12.4 propagation).
 */
export const usePutRoute = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putRoute>>, TError,{data: PutSecretRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putRoute>>,
        TError,
        {data: PutSecretRequest},
        TContext
      > => {
      return useMutation(getPutRouteMutationOptions(options), queryClient);
    }
    export type deleteRouteResponse200 = {
  data: SecretDeleted
  status: 200
}

export type deleteRouteResponse401 = {
  data: void
  status: 401
}

export type deleteRouteResponse403 = {
  data: void
  status: 403
}

export type deleteRouteResponse404 = {
  data: void
  status: 404
}

export type deleteRouteResponseSuccess = (deleteRouteResponse200) & {
  headers: Headers;
};
export type deleteRouteResponseError = (deleteRouteResponse401 | deleteRouteResponse403 | deleteRouteResponse404) & {
  headers: Headers;
};

export type deleteRouteResponse = (deleteRouteResponseSuccess | deleteRouteResponseError)

export const getDeleteRouteUrl = (scope: string,
    name: string,) => {




  return `/api/secrets/${scope}/${name}`
}

/**
 * @summary DELETE /api/secrets/{scope}/{name} (operator+). 404 when absent.
Kicks a render pass: referencing apps' secrets_version changes
(their references stop resolving), so consumers are notified.
 */
export const deleteRoute = async (scope: string,
    name: string, options?: RequestInit): Promise<deleteRouteResponse> => {

  const res = await fetch(getDeleteRouteUrl(scope,name),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteRouteResponse
}





export const getDeleteRouteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{scope: string;name: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{scope: string;name: string}, TContext> => {

const mutationKey = ['deleteRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteRoute>>, {scope: string;name: string}> = (props) => {
          const {scope,name} = props ?? {};

          return  deleteRoute(scope,name,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteRouteMutationResult = NonNullable<Awaited<ReturnType<typeof deleteRoute>>>

    export type DeleteRouteMutationError = void

    /**
 * @summary DELETE /api/secrets/{scope}/{name} (operator+). 404 when absent.
Kicks a render pass: referencing apps' secrets_version changes
(their references stop resolving), so consumers are notified.
 */
export const useDeleteRoute = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteRoute>>, TError,{scope: string;name: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteRoute>>,
        TError,
        {scope: string;name: string},
        TContext
      > => {
      return useMutation(getDeleteRouteMutationOptions(options), queryClient);
    }
