/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateTierTokenRequest,
  CreatedTierToken,
  ErrorBody,
  FederationStatus,
  TierTokenList,
  TierTokenRevoked
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type federationStatusResponse200 = {
  data: FederationStatus
  status: 200
}

export type federationStatusResponse401 = {
  data: void
  status: 401
}

export type federationStatusResponse403 = {
  data: void
  status: 403
}

export type federationStatusResponseSuccess = (federationStatusResponse200) & {
  headers: Headers;
};
export type federationStatusResponseError = (federationStatusResponse401 | federationStatusResponse403) & {
  headers: Headers;
};

export type federationStatusResponse = (federationStatusResponseSuccess | federationStatusResponseError)

export const getFederationStatusUrl = () => {




  return `/api/federation/status`
}

/**
 * @summary GET /api/federation/status (viewer+): this tier's federation state
(§8.2 queryable). Root tiers report mode "root" and their delegated
children; gateways report upstream, sync bookkeeping and cursors.
 */
export const federationStatus = async ( options?: RequestInit): Promise<federationStatusResponse> => {

  const res = await fetch(getFederationStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: federationStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as federationStatusResponse
}





export const getFederationStatusQueryKey = () => {
    return [
    `/api/federation/status`
    ] as const;
    }


export const getFederationStatusQueryOptions = <TData = Awaited<ReturnType<typeof federationStatus>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof federationStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFederationStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof federationStatus>>> = ({ signal }) => federationStatus({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof federationStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FederationStatusQueryResult = NonNullable<Awaited<ReturnType<typeof federationStatus>>>
export type FederationStatusQueryError = void


export function useFederationStatus<TData = Awaited<ReturnType<typeof federationStatus>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof federationStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof federationStatus>>,
          TError,
          Awaited<ReturnType<typeof federationStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFederationStatus<TData = Awaited<ReturnType<typeof federationStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof federationStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof federationStatus>>,
          TError,
          Awaited<ReturnType<typeof federationStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFederationStatus<TData = Awaited<ReturnType<typeof federationStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof federationStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/federation/status (viewer+): this tier's federation state
(§8.2 queryable). Root tiers report mode "root" and their delegated
children; gateways report upstream, sync bookkeeping and cursors.
 */

export function useFederationStatus<TData = Awaited<ReturnType<typeof federationStatus>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof federationStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFederationStatusQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type listTokensRouteResponse200 = {
  data: TierTokenList
  status: 200
}

export type listTokensRouteResponse401 = {
  data: void
  status: 401
}

export type listTokensRouteResponse403 = {
  data: void
  status: 403
}

export type listTokensRouteResponseSuccess = (listTokensRouteResponse200) & {
  headers: Headers;
};
export type listTokensRouteResponseError = (listTokensRouteResponse401 | listTokensRouteResponse403) & {
  headers: Headers;
};

export type listTokensRouteResponse = (listTokensRouteResponseSuccess | listTokensRouteResponseError)

export const getListTokensRouteUrl = () => {




  return `/api/tier-tokens`
}

/**
 * @summary GET /api/tier-tokens (viewer+): metadata, never raw tokens.
 */
export const listTokensRoute = async ( options?: RequestInit): Promise<listTokensRouteResponse> => {

  const res = await fetch(getListTokensRouteUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listTokensRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listTokensRouteResponse
}





export const getListTokensRouteQueryKey = () => {
    return [
    `/api/tier-tokens`
    ] as const;
    }


export const getListTokensRouteQueryOptions = <TData = Awaited<ReturnType<typeof listTokensRoute>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTokensRoute>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListTokensRouteQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listTokensRoute>>> = ({ signal }) => listTokensRoute({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listTokensRoute>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListTokensRouteQueryResult = NonNullable<Awaited<ReturnType<typeof listTokensRoute>>>
export type ListTokensRouteQueryError = void


export function useListTokensRoute<TData = Awaited<ReturnType<typeof listTokensRoute>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTokensRoute>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTokensRoute>>,
          TError,
          Awaited<ReturnType<typeof listTokensRoute>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTokensRoute<TData = Awaited<ReturnType<typeof listTokensRoute>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTokensRoute>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listTokensRoute>>,
          TError,
          Awaited<ReturnType<typeof listTokensRoute>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListTokensRoute<TData = Awaited<ReturnType<typeof listTokensRoute>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTokensRoute>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/tier-tokens (viewer+): metadata, never raw tokens.
 */

export function useListTokensRoute<TData = Awaited<ReturnType<typeof listTokensRoute>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listTokensRoute>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListTokensRouteQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createTokenRouteResponse200 = {
  data: CreatedTierToken
  status: 200
}

export type createTokenRouteResponse401 = {
  data: void
  status: 401
}

export type createTokenRouteResponse403 = {
  data: void
  status: 403
}

export type createTokenRouteResponse409 = {
  data: ErrorBody
  status: 409
}

export type createTokenRouteResponse422 = {
  data: ErrorBody
  status: 422
}

export type createTokenRouteResponseSuccess = (createTokenRouteResponse200) & {
  headers: Headers;
};
export type createTokenRouteResponseError = (createTokenRouteResponse401 | createTokenRouteResponse403 | createTokenRouteResponse409 | createTokenRouteResponse422) & {
  headers: Headers;
};

export type createTokenRouteResponse = (createTokenRouteResponseSuccess | createTokenRouteResponseError)

export const getCreateTokenRouteUrl = () => {




  return `/api/tier-tokens`
}

/**
 * @summary POST /api/tier-tokens (admin — §8.7 "issued like join tokens by
admin"). Returns the raw token ONCE.
 */
export const createTokenRoute = async (createTierTokenRequest: CreateTierTokenRequest, options?: RequestInit): Promise<createTokenRouteResponse> => {

  const res = await fetch(getCreateTokenRouteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createTierTokenRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createTokenRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createTokenRouteResponse
}





export const getCreateTokenRouteMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTokenRoute>>, TError,{data: CreateTierTokenRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createTokenRoute>>, TError,{data: CreateTierTokenRequest}, TContext> => {

const mutationKey = ['createTokenRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createTokenRoute>>, {data: CreateTierTokenRequest}> = (props) => {
          const {data} = props ?? {};

          return  createTokenRoute(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateTokenRouteMutationResult = NonNullable<Awaited<ReturnType<typeof createTokenRoute>>>
    export type CreateTokenRouteMutationBody = CreateTierTokenRequest
    export type CreateTokenRouteMutationError = void | ErrorBody

    /**
 * @summary POST /api/tier-tokens (admin — §8.7 "issued like join tokens by
admin"). Returns the raw token ONCE.
 */
export const useCreateTokenRoute = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createTokenRoute>>, TError,{data: CreateTierTokenRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createTokenRoute>>,
        TError,
        {data: CreateTierTokenRequest},
        TContext
      > => {
      return useMutation(getCreateTokenRouteMutationOptions(options), queryClient);
    }
    export type revokeTokenRouteResponse200 = {
  data: TierTokenRevoked
  status: 200
}

export type revokeTokenRouteResponse401 = {
  data: void
  status: 401
}

export type revokeTokenRouteResponse403 = {
  data: void
  status: 403
}

export type revokeTokenRouteResponseSuccess = (revokeTokenRouteResponse200) & {
  headers: Headers;
};
export type revokeTokenRouteResponseError = (revokeTokenRouteResponse401 | revokeTokenRouteResponse403) & {
  headers: Headers;
};

export type revokeTokenRouteResponse = (revokeTokenRouteResponseSuccess | revokeTokenRouteResponseError)

export const getRevokeTokenRouteUrl = (name: string,) => {




  return `/api/tier-tokens/${name}`
}

/**
 * @summary DELETE /api/tier-tokens/{name} (admin): revoke. Idempotent.
 */
export const revokeTokenRoute = async (name: string, options?: RequestInit): Promise<revokeTokenRouteResponse> => {

  const res = await fetch(getRevokeTokenRouteUrl(name),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: revokeTokenRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as revokeTokenRouteResponse
}





export const getRevokeTokenRouteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeTokenRoute>>, TError,{name: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof revokeTokenRoute>>, TError,{name: string}, TContext> => {

const mutationKey = ['revokeTokenRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeTokenRoute>>, {name: string}> = (props) => {
          const {name} = props ?? {};

          return  revokeTokenRoute(name,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeTokenRouteMutationResult = NonNullable<Awaited<ReturnType<typeof revokeTokenRoute>>>

    export type RevokeTokenRouteMutationError = void

    /**
 * @summary DELETE /api/tier-tokens/{name} (admin): revoke. Idempotent.
 */
export const useRevokeTokenRoute = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeTokenRoute>>, TError,{name: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof revokeTokenRoute>>,
        TError,
        {name: string},
        TContext
      > => {
      return useMutation(getRevokeTokenRouteMutationOptions(options), queryClient);
    }
