/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateRequest,
  CreateRolloutResponse,
  ErrorBody,
  RolloutDetail,
  RolloutSummary,
  RolloutTransitioned
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type listRolloutsResponse200 = {
  data: RolloutSummary[]
  status: 200
}

export type listRolloutsResponse401 = {
  data: void
  status: 401
}

export type listRolloutsResponse403 = {
  data: void
  status: 403
}

export type listRolloutsResponseSuccess = (listRolloutsResponse200) & {
  headers: Headers;
};
export type listRolloutsResponseError = (listRolloutsResponse401 | listRolloutsResponse403) & {
  headers: Headers;
};

export type listRolloutsResponse = (listRolloutsResponseSuccess | listRolloutsResponseError)

export const getListRolloutsUrl = () => {




  return `/api/rollouts`
}

/**
 * @summary GET /api/rollouts (viewer+) — newest first.
 */
export const listRollouts = async ( options?: RequestInit): Promise<listRolloutsResponse> => {

  const res = await fetch(getListRolloutsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: listRolloutsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as listRolloutsResponse
}





export const getListRolloutsQueryKey = () => {
    return [
    `/api/rollouts`
    ] as const;
    }


export const getListRolloutsQueryOptions = <TData = Awaited<ReturnType<typeof listRollouts>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRollouts>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListRolloutsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof listRollouts>>> = ({ signal }) => listRollouts({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listRollouts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListRolloutsQueryResult = NonNullable<Awaited<ReturnType<typeof listRollouts>>>
export type ListRolloutsQueryError = void


export function useListRollouts<TData = Awaited<ReturnType<typeof listRollouts>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRollouts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRollouts>>,
          TError,
          Awaited<ReturnType<typeof listRollouts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRollouts<TData = Awaited<ReturnType<typeof listRollouts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRollouts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listRollouts>>,
          TError,
          Awaited<ReturnType<typeof listRollouts>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListRollouts<TData = Awaited<ReturnType<typeof listRollouts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRollouts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/rollouts (viewer+) — newest first.
 */

export function useListRollouts<TData = Awaited<ReturnType<typeof listRollouts>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listRollouts>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListRolloutsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type createRouteResponse201 = {
  data: CreateRolloutResponse
  status: 201
}

export type createRouteResponse401 = {
  data: void
  status: 401
}

export type createRouteResponse403 = {
  data: void
  status: 403
}

export type createRouteResponse409 = {
  data: ErrorBody
  status: 409
}

export type createRouteResponse422 = {
  data: ErrorBody
  status: 422
}

export type createRouteResponseSuccess = (createRouteResponse201) & {
  headers: Headers;
};
export type createRouteResponseError = (createRouteResponse401 | createRouteResponse403 | createRouteResponse409 | createRouteResponse422) & {
  headers: Headers;
};

export type createRouteResponse = (createRouteResponseSuccess | createRouteResponseError)

export const getCreateRouteUrl = () => {




  return `/api/rollouts`
}

/**
 * DECISION (baseline): un-advanced cohort devices are held at
 * `baselineRevision` (default: the target revision's parent). The
 * authoring commit has usually already rendered every device at head
 * by the time the rollout is created (tree.rs render hook), so
 * creation re-pins cohort devices to the baseline render; devices
 * that polled in the gap converge back to it. manifestVersion stays
 * strictly monotonic throughout (§11.5 note — content may revert,
 * versions never do). Create the rollout promptly after the commit
 * and no device ever sees the staged content early.
 * @summary POST /api/rollouts (operator+) — create and immediately start.
 */
export const createRoute = async (createRequest: CreateRequest, options?: RequestInit): Promise<createRouteResponse> => {

  const res = await fetch(getCreateRouteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createRouteResponse
}





export const getCreateRouteMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoute>>, TError,{data: CreateRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createRoute>>, TError,{data: CreateRequest}, TContext> => {

const mutationKey = ['createRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createRoute>>, {data: CreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  createRoute(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateRouteMutationResult = NonNullable<Awaited<ReturnType<typeof createRoute>>>
    export type CreateRouteMutationBody = CreateRequest
    export type CreateRouteMutationError = void | ErrorBody

    /**
 * @summary POST /api/rollouts (operator+) — create and immediately start.
 */
export const useCreateRoute = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createRoute>>, TError,{data: CreateRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createRoute>>,
        TError,
        {data: CreateRequest},
        TContext
      > => {
      return useMutation(getCreateRouteMutationOptions(options), queryClient);
    }
    export type rolloutStatusResponse200 = {
  data: RolloutDetail
  status: 200
}

export type rolloutStatusResponse401 = {
  data: void
  status: 401
}

export type rolloutStatusResponse403 = {
  data: void
  status: 403
}

export type rolloutStatusResponse404 = {
  data: ErrorBody
  status: 404
}

export type rolloutStatusResponseSuccess = (rolloutStatusResponse200) & {
  headers: Headers;
};
export type rolloutStatusResponseError = (rolloutStatusResponse401 | rolloutStatusResponse403 | rolloutStatusResponse404) & {
  headers: Headers;
};

export type rolloutStatusResponse = (rolloutStatusResponseSuccess | rolloutStatusResponseError)

export const getRolloutStatusUrl = (rolloutId: string,) => {




  return `/api/rollouts/${rolloutId}`
}

/**
 * @summary GET /api/rollouts/{id} (viewer+) — full status: waves with live
per-device classification (§11.6: advanced / converged /
undetermined / failed), the pinned/unaffected count (§11.1 MUST),
recorded gate results, and the transition history.
 */
export const rolloutStatus = async (rolloutId: string, options?: RequestInit): Promise<rolloutStatusResponse> => {

  const res = await fetch(getRolloutStatusUrl(rolloutId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: rolloutStatusResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as rolloutStatusResponse
}





export const getRolloutStatusQueryKey = (rolloutId: string,) => {
    return [
    `/api/rollouts/${rolloutId}`
    ] as const;
    }


export const getRolloutStatusQueryOptions = <TData = Awaited<ReturnType<typeof rolloutStatus>>, TError = void | ErrorBody>(rolloutId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolloutStatus>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getRolloutStatusQueryKey(rolloutId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof rolloutStatus>>> = ({ signal }) => rolloutStatus(rolloutId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: rolloutId !== null && rolloutId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof rolloutStatus>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type RolloutStatusQueryResult = NonNullable<Awaited<ReturnType<typeof rolloutStatus>>>
export type RolloutStatusQueryError = void | ErrorBody


export function useRolloutStatus<TData = Awaited<ReturnType<typeof rolloutStatus>>, TError = void | ErrorBody>(
 rolloutId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolloutStatus>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolloutStatus>>,
          TError,
          Awaited<ReturnType<typeof rolloutStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolloutStatus<TData = Awaited<ReturnType<typeof rolloutStatus>>, TError = void | ErrorBody>(
 rolloutId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolloutStatus>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof rolloutStatus>>,
          TError,
          Awaited<ReturnType<typeof rolloutStatus>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useRolloutStatus<TData = Awaited<ReturnType<typeof rolloutStatus>>, TError = void | ErrorBody>(
 rolloutId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolloutStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/rollouts/{id} (viewer+) — full status: waves with live
per-device classification (§11.6: advanced / converged /
undetermined / failed), the pinned/unaffected count (§11.1 MUST),
recorded gate results, and the transition history.
 */

export function useRolloutStatus<TData = Awaited<ReturnType<typeof rolloutStatus>>, TError = void | ErrorBody>(
 rolloutId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof rolloutStatus>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getRolloutStatusQueryOptions(rolloutId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type abortRouteResponse200 = {
  data: RolloutTransitioned
  status: 200
}

export type abortRouteResponse401 = {
  data: void
  status: 401
}

export type abortRouteResponse403 = {
  data: void
  status: 403
}

export type abortRouteResponse404 = {
  data: ErrorBody
  status: 404
}

export type abortRouteResponse409 = {
  data: ErrorBody
  status: 409
}

export type abortRouteResponseSuccess = (abortRouteResponse200) & {
  headers: Headers;
};
export type abortRouteResponseError = (abortRouteResponse401 | abortRouteResponse403 | abortRouteResponse404 | abortRouteResponse409) & {
  headers: Headers;
};

export type abortRouteResponse = (abortRouteResponseSuccess | abortRouteResponseError)

export const getAbortRouteUrl = (rolloutId: string,) => {




  return `/api/rollouts/${rolloutId}/abort`
}

/**
 * @summary POST /api/rollouts/{id}/abort (operator+).
 */
export const abortRoute = async (rolloutId: string, options?: RequestInit): Promise<abortRouteResponse> => {

  const res = await fetch(getAbortRouteUrl(rolloutId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: abortRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as abortRouteResponse
}





export const getAbortRouteMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof abortRoute>>, TError,{rolloutId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof abortRoute>>, TError,{rolloutId: string}, TContext> => {

const mutationKey = ['abortRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof abortRoute>>, {rolloutId: string}> = (props) => {
          const {rolloutId} = props ?? {};

          return  abortRoute(rolloutId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AbortRouteMutationResult = NonNullable<Awaited<ReturnType<typeof abortRoute>>>

    export type AbortRouteMutationError = void | ErrorBody

    /**
 * @summary POST /api/rollouts/{id}/abort (operator+).
 */
export const useAbortRoute = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof abortRoute>>, TError,{rolloutId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof abortRoute>>,
        TError,
        {rolloutId: string},
        TContext
      > => {
      return useMutation(getAbortRouteMutationOptions(options), queryClient);
    }
    export type pauseRouteResponse200 = {
  data: RolloutTransitioned
  status: 200
}

export type pauseRouteResponse401 = {
  data: void
  status: 401
}

export type pauseRouteResponse403 = {
  data: void
  status: 403
}

export type pauseRouteResponse404 = {
  data: ErrorBody
  status: 404
}

export type pauseRouteResponse409 = {
  data: ErrorBody
  status: 409
}

export type pauseRouteResponseSuccess = (pauseRouteResponse200) & {
  headers: Headers;
};
export type pauseRouteResponseError = (pauseRouteResponse401 | pauseRouteResponse403 | pauseRouteResponse404 | pauseRouteResponse409) & {
  headers: Headers;
};

export type pauseRouteResponse = (pauseRouteResponseSuccess | pauseRouteResponseError)

export const getPauseRouteUrl = (rolloutId: string,) => {




  return `/api/rollouts/${rolloutId}/pause`
}

/**
 * @summary POST /api/rollouts/{id}/pause (operator+).
 */
export const pauseRoute = async (rolloutId: string, options?: RequestInit): Promise<pauseRouteResponse> => {

  const res = await fetch(getPauseRouteUrl(rolloutId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: pauseRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as pauseRouteResponse
}





export const getPauseRouteMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseRoute>>, TError,{rolloutId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof pauseRoute>>, TError,{rolloutId: string}, TContext> => {

const mutationKey = ['pauseRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof pauseRoute>>, {rolloutId: string}> = (props) => {
          const {rolloutId} = props ?? {};

          return  pauseRoute(rolloutId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PauseRouteMutationResult = NonNullable<Awaited<ReturnType<typeof pauseRoute>>>

    export type PauseRouteMutationError = void | ErrorBody

    /**
 * @summary POST /api/rollouts/{id}/pause (operator+).
 */
export const usePauseRoute = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof pauseRoute>>, TError,{rolloutId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof pauseRoute>>,
        TError,
        {rolloutId: string},
        TContext
      > => {
      return useMutation(getPauseRouteMutationOptions(options), queryClient);
    }
    export type resumeRouteResponse200 = {
  data: RolloutTransitioned
  status: 200
}

export type resumeRouteResponse401 = {
  data: void
  status: 401
}

export type resumeRouteResponse403 = {
  data: void
  status: 403
}

export type resumeRouteResponse404 = {
  data: ErrorBody
  status: 404
}

export type resumeRouteResponse409 = {
  data: ErrorBody
  status: 409
}

export type resumeRouteResponseSuccess = (resumeRouteResponse200) & {
  headers: Headers;
};
export type resumeRouteResponseError = (resumeRouteResponse401 | resumeRouteResponse403 | resumeRouteResponse404 | resumeRouteResponse409) & {
  headers: Headers;
};

export type resumeRouteResponse = (resumeRouteResponseSuccess | resumeRouteResponseError)

export const getResumeRouteUrl = (rolloutId: string,) => {




  return `/api/rollouts/${rolloutId}/resume`
}

/**
 * @summary POST /api/rollouts/{id}/resume (operator+).
 */
export const resumeRoute = async (rolloutId: string, options?: RequestInit): Promise<resumeRouteResponse> => {

  const res = await fetch(getResumeRouteUrl(rolloutId),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: resumeRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resumeRouteResponse
}





export const getResumeRouteMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeRoute>>, TError,{rolloutId: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof resumeRoute>>, TError,{rolloutId: string}, TContext> => {

const mutationKey = ['resumeRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resumeRoute>>, {rolloutId: string}> = (props) => {
          const {rolloutId} = props ?? {};

          return  resumeRoute(rolloutId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResumeRouteMutationResult = NonNullable<Awaited<ReturnType<typeof resumeRoute>>>

    export type ResumeRouteMutationError = void | ErrorBody

    /**
 * @summary POST /api/rollouts/{id}/resume (operator+).
 */
export const useResumeRoute = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resumeRoute>>, TError,{rolloutId: string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resumeRoute>>,
        TError,
        {rolloutId: string},
        TContext
      > => {
      return useMutation(getResumeRouteMutationOptions(options), queryClient);
    }
