/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  DeploymentStatusManifest,
  ErrorBody,
  JournalAck,
  JournalBatch,
  SecretsResolveRequest,
  SecretsResolveResponse,
  ServerCapabilities,
  StateManifest
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type capabilitiesResponse200 = {
  data: ServerCapabilities
  status: 200
}

export type capabilitiesResponse401 = {
  data: void
  status: 401
}

export type capabilitiesResponseSuccess = (capabilitiesResponse200) & {
  headers: Headers;
};
export type capabilitiesResponseError = (capabilitiesResponse401) & {
  headers: Headers;
};

export type capabilitiesResponse = (capabilitiesResponseSuccess | capabilitiesResponseError)

export const getCapabilitiesUrl = () => {




  return `/api/reeve/v1/capabilities`
}

/**
 * @summary GET /api/reeve/v1/capabilities (device-auth'd; anonymous pull of
anything device-facing is disabled by default, §10.2).
 */
export const capabilities = async ( options?: RequestInit): Promise<capabilitiesResponse> => {

  const res = await fetch(getCapabilitiesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: capabilitiesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as capabilitiesResponse
}





export const getCapabilitiesQueryKey = () => {
    return [
    `/api/reeve/v1/capabilities`
    ] as const;
    }


export const getCapabilitiesQueryOptions = <TData = Awaited<ReturnType<typeof capabilities>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof capabilities>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getCapabilitiesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof capabilities>>> = ({ signal }) => capabilities({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof capabilities>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type CapabilitiesQueryResult = NonNullable<Awaited<ReturnType<typeof capabilities>>>
export type CapabilitiesQueryError = void


export function useCapabilities<TData = Awaited<ReturnType<typeof capabilities>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof capabilities>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof capabilities>>,
          TError,
          Awaited<ReturnType<typeof capabilities>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCapabilities<TData = Awaited<ReturnType<typeof capabilities>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof capabilities>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof capabilities>>,
          TError,
          Awaited<ReturnType<typeof capabilities>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useCapabilities<TData = Awaited<ReturnType<typeof capabilities>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof capabilities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/reeve/v1/capabilities (device-auth'd; anonymous pull of
anything device-facing is disabled by default, §10.2).
 */

export function useCapabilities<TData = Awaited<ReturnType<typeof capabilities>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof capabilities>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getCapabilitiesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type journalBackfillResponse200 = {
  data: JournalAck
  status: 200
}

export type journalBackfillResponse401 = {
  data: void
  status: 401
}

export type journalBackfillResponse403 = {
  data: ErrorBody
  status: 403
}

export type journalBackfillResponse422 = {
  data: ErrorBody
  status: 422
}

export type journalBackfillResponseSuccess = (journalBackfillResponse200) & {
  headers: Headers;
};
export type journalBackfillResponseError = (journalBackfillResponse401 | journalBackfillResponse403 | journalBackfillResponse422) & {
  headers: Headers;
};

export type journalBackfillResponse = (journalBackfillResponseSuccess | journalBackfillResponseError)

export const getJournalBackfillUrl = (deviceId: string,) => {




  return `/api/reeve/v1/journal/${deviceId}`
}

/**
 * @summary POST /api/reeve/v1/journal/{deviceId} — backfill batch
(spec/reeve/05-health-journal.md §7.3). Replies [`JournalAck`]: the
highest contiguously ingested seq, which is what permits agent-side
journal eviction (§7.1).
 */
export const journalBackfill = async (deviceId: string,
    journalBatch: JournalBatch, options?: RequestInit): Promise<journalBackfillResponse> => {

  const res = await fetch(getJournalBackfillUrl(deviceId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(journalBatch)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: journalBackfillResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as journalBackfillResponse
}





export const getJournalBackfillMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof journalBackfill>>, TError,{deviceId: string;data: JournalBatch}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof journalBackfill>>, TError,{deviceId: string;data: JournalBatch}, TContext> => {

const mutationKey = ['journalBackfill'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof journalBackfill>>, {deviceId: string;data: JournalBatch}> = (props) => {
          const {deviceId,data} = props ?? {};

          return  journalBackfill(deviceId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type JournalBackfillMutationResult = NonNullable<Awaited<ReturnType<typeof journalBackfill>>>
    export type JournalBackfillMutationBody = JournalBatch
    export type JournalBackfillMutationError = void | ErrorBody

    /**
 * @summary POST /api/reeve/v1/journal/{deviceId} — backfill batch
(spec/reeve/05-health-journal.md §7.3). Replies [`JournalAck`]: the
highest contiguously ingested seq, which is what permits agent-side
journal eviction (§7.1).
 */
export const useJournalBackfill = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof journalBackfill>>, TError,{deviceId: string;data: JournalBatch}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof journalBackfill>>,
        TError,
        {deviceId: string;data: JournalBatch},
        TContext
      > => {
      return useMutation(getJournalBackfillMutationOptions(options), queryClient);
    }
    export type manifestResponse200 = {
  data: StateManifest
  status: 200
}

export type manifestResponse304 = {
  data: void
  status: 304
}

export type manifestResponse401 = {
  data: void
  status: 401
}

export type manifestResponse404 = {
  data: ErrorBody
  status: 404
}

export type manifestResponseSuccess = (manifestResponse200) & {
  headers: Headers;
};
export type manifestResponseError = (manifestResponse304 | manifestResponse401 | manifestResponse404) & {
  headers: Headers;
};

export type manifestResponse = (manifestResponseSuccess | manifestResponseError)

export const getManifestUrl = () => {




  return `/api/reeve/v1/manifest`
}

/**
 * @summary GET /api/reeve/v1/manifest — the device-scoped State Manifest
(§10.2). Renders on demand when the device's row is behind the
local head (fresh enrollment, missed pass), then serves the stored
manifest bytes verbatim so the ETag is exact.
 */
export const manifest = async ( options?: RequestInit): Promise<manifestResponse> => {

  const res = await fetch(getManifestUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: manifestResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as manifestResponse
}





export const getManifestQueryKey = () => {
    return [
    `/api/reeve/v1/manifest`
    ] as const;
    }


export const getManifestQueryOptions = <TData = Awaited<ReturnType<typeof manifest>>, TError = void | ErrorBody>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manifest>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getManifestQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof manifest>>> = ({ signal }) => manifest({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof manifest>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ManifestQueryResult = NonNullable<Awaited<ReturnType<typeof manifest>>>
export type ManifestQueryError = void | ErrorBody


export function useManifest<TData = Awaited<ReturnType<typeof manifest>>, TError = void | ErrorBody>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof manifest>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof manifest>>,
          TError,
          Awaited<ReturnType<typeof manifest>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useManifest<TData = Awaited<ReturnType<typeof manifest>>, TError = void | ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manifest>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof manifest>>,
          TError,
          Awaited<ReturnType<typeof manifest>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useManifest<TData = Awaited<ReturnType<typeof manifest>>, TError = void | ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manifest>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/reeve/v1/manifest — the device-scoped State Manifest
(§10.2). Renders on demand when the device's row is behind the
local head (fresh enrollment, missed pass), then serves the stored
manifest bytes verbatim so the ETag is exact.
 */

export function useManifest<TData = Awaited<ReturnType<typeof manifest>>, TError = void | ErrorBody>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof manifest>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getManifestQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type resolveRouteResponse200 = {
  data: SecretsResolveResponse
  status: 200
}

export type resolveRouteResponse401 = {
  data: void
  status: 401
}

export type resolveRouteResponse404 = {
  data: void
  status: 404
}

export type resolveRouteResponseSuccess = (resolveRouteResponse200) & {
  headers: Headers;
};
export type resolveRouteResponseError = (resolveRouteResponse401 | resolveRouteResponse404) & {
  headers: Headers;
};

export type resolveRouteResponse = (resolveRouteResponseSuccess | resolveRouteResponseError)

export const getResolveRouteUrl = () => {




  return `/api/reeve/v1/secrets/resolve`
}

/**
 * @summary POST /api/reeve/v1/secrets/resolve (device auth; §12.3/§12.6).
The device receives exactly its own resolution: names resolve down
ITS chain; unknown/unscoped names are absent from the response.
 */
export const resolveRoute = async (secretsResolveRequest: SecretsResolveRequest, options?: RequestInit): Promise<resolveRouteResponse> => {

  const res = await fetch(getResolveRouteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(secretsResolveRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: resolveRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as resolveRouteResponse
}





export const getResolveRouteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveRoute>>, TError,{data: SecretsResolveRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof resolveRoute>>, TError,{data: SecretsResolveRequest}, TContext> => {

const mutationKey = ['resolveRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof resolveRoute>>, {data: SecretsResolveRequest}> = (props) => {
          const {data} = props ?? {};

          return  resolveRoute(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ResolveRouteMutationResult = NonNullable<Awaited<ReturnType<typeof resolveRoute>>>
    export type ResolveRouteMutationBody = SecretsResolveRequest
    export type ResolveRouteMutationError = void

    /**
 * @summary POST /api/reeve/v1/secrets/resolve (device auth; §12.3/§12.6).
The device receives exactly its own resolution: names resolve down
ITS chain; unknown/unscoped names are absent from the response.
 */
export const useResolveRoute = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof resolveRoute>>, TError,{data: SecretsResolveRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof resolveRoute>>,
        TError,
        {data: SecretsResolveRequest},
        TContext
      > => {
      return useMutation(getResolveRouteMutationOptions(options), queryClient);
    }
    export type deploymentStatusResponse200 = {
  data: void
  status: 200
}

export type deploymentStatusResponse400 = {
  data: ErrorBody
  status: 400
}

export type deploymentStatusResponse401 = {
  data: void
  status: 401
}

export type deploymentStatusResponse403 = {
  data: ErrorBody
  status: 403
}

export type deploymentStatusResponse422 = {
  data: ErrorBody
  status: 422
}

export type deploymentStatusResponseSuccess = (deploymentStatusResponse200) & {
  headers: Headers;
};
export type deploymentStatusResponseError = (deploymentStatusResponse400 | deploymentStatusResponse401 | deploymentStatusResponse403 | deploymentStatusResponse422) & {
  headers: Headers;
};

export type deploymentStatusResponse = (deploymentStatusResponseSuccess | deploymentStatusResponseError)

export const getDeploymentStatusUrl = (clientId: string,
    deploymentId: string,) => {




  return `/api/v1/clients/${clientId}/deployments/${deploymentId}/status`
}

/**
 * @summary POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status —
Margo live path. Response codes per `deployment-status.md`: 200
added/updated, 400 malformed, 401 unauthenticated (middleware),
403 wrong device, 422 semantic error.
 */
export const deploymentStatus = async (clientId: string,
    deploymentId: string,
    deploymentStatusManifest: DeploymentStatusManifest, options?: RequestInit): Promise<deploymentStatusResponse> => {

  const res = await fetch(getDeploymentStatusUrl(clientId,deploymentId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(deploymentStatusManifest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deploymentStatusResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deploymentStatusResponse
}





export const getDeploymentStatusMutationOptions = <TError = ErrorBody | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deploymentStatus>>, TError,{clientId: string;deploymentId: string;data: DeploymentStatusManifest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deploymentStatus>>, TError,{clientId: string;deploymentId: string;data: DeploymentStatusManifest}, TContext> => {

const mutationKey = ['deploymentStatus'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deploymentStatus>>, {clientId: string;deploymentId: string;data: DeploymentStatusManifest}> = (props) => {
          const {clientId,deploymentId,data} = props ?? {};

          return  deploymentStatus(clientId,deploymentId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeploymentStatusMutationResult = NonNullable<Awaited<ReturnType<typeof deploymentStatus>>>
    export type DeploymentStatusMutationBody = DeploymentStatusManifest
    export type DeploymentStatusMutationError = ErrorBody | void

    /**
 * @summary POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status —
Margo live path. Response codes per `deployment-status.md`: 200
added/updated, 400 malformed, 401 unauthenticated (middleware),
403 wrong device, 422 semantic error.
 */
export const useDeploymentStatus = <TError = ErrorBody | void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deploymentStatus>>, TError,{clientId: string;deploymentId: string;data: DeploymentStatusManifest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deploymentStatus>>,
        TError,
        {clientId: string;deploymentId: string;data: DeploymentStatusManifest},
        TContext
      > => {
      return useMutation(getDeploymentStatusMutationOptions(options), queryClient);
    }
