/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateGroupRequest,
  ErrorBody,
  GroupNode,
  GroupTree,
  GroupsListParams,
  RenameGroupRequest
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type groupsListResponse200 = {
  data: GroupTree
  status: 200
}

export type groupsListResponse401 = {
  data: void
  status: 401
}

export type groupsListResponse403 = {
  data: void
  status: 403
}

export type groupsListResponse404 = {
  data: ErrorBody
  status: 404
}

export type groupsListResponseSuccess = (groupsListResponse200) & {
  headers: Headers;
};
export type groupsListResponseError = (groupsListResponse401 | groupsListResponse403 | groupsListResponse404) & {
  headers: Headers;
};

export type groupsListResponse = (groupsListResponseSuccess | groupsListResponseError)

export const getGroupsListUrl = (params?: GroupsListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/groups?${stringifiedParams}` : `/api/groups`
}

/**
 * @summary GET /api/groups (viewer+) — the fleet->site containment tree.
`?fleet=<name>` (optionally `&kind=site`) scopes the read to one
fleet's children (lazy drill-down).
 */
export const groupsList = async (params?: GroupsListParams, options?: RequestInit): Promise<groupsListResponse> => {

  const res = await fetch(getGroupsListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: groupsListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as groupsListResponse
}





export const getGroupsListQueryKey = (params?: GroupsListParams,) => {
    return [
    `/api/groups`, ...(params ? [params] : [])
    ] as const;
    }


export const getGroupsListQueryOptions = <TData = Awaited<ReturnType<typeof groupsList>>, TError = void | ErrorBody>(params?: GroupsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupsList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGroupsListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof groupsList>>> = ({ signal }) => groupsList(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof groupsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GroupsListQueryResult = NonNullable<Awaited<ReturnType<typeof groupsList>>>
export type GroupsListQueryError = void | ErrorBody


export function useGroupsList<TData = Awaited<ReturnType<typeof groupsList>>, TError = void | ErrorBody>(
 params: undefined |  GroupsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupsList>>,
          TError,
          Awaited<ReturnType<typeof groupsList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupsList<TData = Awaited<ReturnType<typeof groupsList>>, TError = void | ErrorBody>(
 params?: GroupsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof groupsList>>,
          TError,
          Awaited<ReturnType<typeof groupsList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGroupsList<TData = Awaited<ReturnType<typeof groupsList>>, TError = void | ErrorBody>(
 params?: GroupsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupsList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/groups (viewer+) — the fleet->site containment tree.
`?fleet=<name>` (optionally `&kind=site`) scopes the read to one
fleet's children (lazy drill-down).
 */

export function useGroupsList<TData = Awaited<ReturnType<typeof groupsList>>, TError = void | ErrorBody>(
 params?: GroupsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof groupsList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGroupsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type groupsCreateResponse201 = {
  data: GroupNode
  status: 201
}

export type groupsCreateResponse401 = {
  data: void
  status: 401
}

export type groupsCreateResponse403 = {
  data: void
  status: 403
}

export type groupsCreateResponse409 = {
  data: ErrorBody
  status: 409
}

export type groupsCreateResponse422 = {
  data: ErrorBody
  status: 422
}

export type groupsCreateResponseSuccess = (groupsCreateResponse201) & {
  headers: Headers;
};
export type groupsCreateResponseError = (groupsCreateResponse401 | groupsCreateResponse403 | groupsCreateResponse409 | groupsCreateResponse422) & {
  headers: Headers;
};

export type groupsCreateResponse = (groupsCreateResponseSuccess | groupsCreateResponseError)

export const getGroupsCreateUrl = () => {




  return `/api/groups`
}

/**
 * @summary POST /api/groups (operator+) — create a fleet or a site. A site
requires `parentId` = an existing fleet; a fleet must have none.
Duplicate name (a fleet globally, a site within its fleet) => 409.
 */
export const groupsCreate = async (createGroupRequest: CreateGroupRequest, options?: RequestInit): Promise<groupsCreateResponse> => {

  const res = await fetch(getGroupsCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createGroupRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: groupsCreateResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as groupsCreateResponse
}





export const getGroupsCreateMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupsCreate>>, TError,{data: CreateGroupRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof groupsCreate>>, TError,{data: CreateGroupRequest}, TContext> => {

const mutationKey = ['groupsCreate'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof groupsCreate>>, {data: CreateGroupRequest}> = (props) => {
          const {data} = props ?? {};

          return  groupsCreate(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GroupsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof groupsCreate>>>
    export type GroupsCreateMutationBody = CreateGroupRequest
    export type GroupsCreateMutationError = void | ErrorBody

    /**
 * @summary POST /api/groups (operator+) — create a fleet or a site. A site
requires `parentId` = an existing fleet; a fleet must have none.
Duplicate name (a fleet globally, a site within its fleet) => 409.
 */
export const useGroupsCreate = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupsCreate>>, TError,{data: CreateGroupRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof groupsCreate>>,
        TError,
        {data: CreateGroupRequest},
        TContext
      > => {
      return useMutation(getGroupsCreateMutationOptions(options), queryClient);
    }
    export type groupsDeleteResponse204 = {
  data: void
  status: 204
}

export type groupsDeleteResponse401 = {
  data: void
  status: 401
}

export type groupsDeleteResponse403 = {
  data: void
  status: 403
}

export type groupsDeleteResponse404 = {
  data: ErrorBody
  status: 404
}

export type groupsDeleteResponse409 = {
  data: ErrorBody
  status: 409
}

export type groupsDeleteResponseSuccess = (groupsDeleteResponse204) & {
  headers: Headers;
};
export type groupsDeleteResponseError = (groupsDeleteResponse401 | groupsDeleteResponse403 | groupsDeleteResponse404 | groupsDeleteResponse409) & {
  headers: Headers;
};

export type groupsDeleteResponse = (groupsDeleteResponseSuccess | groupsDeleteResponseError)

export const getGroupsDeleteUrl = (id: number,) => {




  return `/api/groups/${id}`
}

/**
 * @summary DELETE /api/groups/{id} (operator+) — delete a group. Refused (409)
when it is still referenced by a device (or, for a fleet, still has
child sites): refuse is safer than a silent cascade that would orphan
live assignments — reassign/remove first.
 */
export const groupsDelete = async (id: number, options?: RequestInit): Promise<groupsDeleteResponse> => {

  const res = await fetch(getGroupsDeleteUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: groupsDeleteResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as groupsDeleteResponse
}





export const getGroupsDeleteMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupsDelete>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof groupsDelete>>, TError,{id: number}, TContext> => {

const mutationKey = ['groupsDelete'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof groupsDelete>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  groupsDelete(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GroupsDeleteMutationResult = NonNullable<Awaited<ReturnType<typeof groupsDelete>>>

    export type GroupsDeleteMutationError = void | ErrorBody

    /**
 * @summary DELETE /api/groups/{id} (operator+) — delete a group. Refused (409)
when it is still referenced by a device (or, for a fleet, still has
child sites): refuse is safer than a silent cascade that would orphan
live assignments — reassign/remove first.
 */
export const useGroupsDelete = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupsDelete>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof groupsDelete>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getGroupsDeleteMutationOptions(options), queryClient);
    }
    export type groupsRenameResponse200 = {
  data: GroupNode
  status: 200
}

export type groupsRenameResponse401 = {
  data: void
  status: 401
}

export type groupsRenameResponse403 = {
  data: void
  status: 403
}

export type groupsRenameResponse404 = {
  data: ErrorBody
  status: 404
}

export type groupsRenameResponse409 = {
  data: ErrorBody
  status: 409
}

export type groupsRenameResponse422 = {
  data: ErrorBody
  status: 422
}

export type groupsRenameResponseSuccess = (groupsRenameResponse200) & {
  headers: Headers;
};
export type groupsRenameResponseError = (groupsRenameResponse401 | groupsRenameResponse403 | groupsRenameResponse404 | groupsRenameResponse409 | groupsRenameResponse422) & {
  headers: Headers;
};

export type groupsRenameResponse = (groupsRenameResponseSuccess | groupsRenameResponseError)

export const getGroupsRenameUrl = (id: number,) => {




  return `/api/groups/${id}`
}

/**
 * @summary PATCH /api/groups/{id} (operator+) — rename a group. Refused (409) when
the group is still referenced by a device (or, for a fleet, still has
child sites): the device name columns stay valid because a live name is
never changed out from under them — reassign first. A rename that
collides with a sibling is also 409.
 */
export const groupsRename = async (id: number,
    renameGroupRequest: RenameGroupRequest, options?: RequestInit): Promise<groupsRenameResponse> => {

  const res = await fetch(getGroupsRenameUrl(id),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(renameGroupRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: groupsRenameResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as groupsRenameResponse
}





export const getGroupsRenameMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupsRename>>, TError,{id: number;data: RenameGroupRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof groupsRename>>, TError,{id: number;data: RenameGroupRequest}, TContext> => {

const mutationKey = ['groupsRename'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof groupsRename>>, {id: number;data: RenameGroupRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  groupsRename(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type GroupsRenameMutationResult = NonNullable<Awaited<ReturnType<typeof groupsRename>>>
    export type GroupsRenameMutationBody = RenameGroupRequest
    export type GroupsRenameMutationError = void | ErrorBody

    /**
 * @summary PATCH /api/groups/{id} (operator+) — rename a group. Refused (409) when
the group is still referenced by a device (or, for a fleet, still has
child sites): the device name columns stay valid because a live name is
never changed out from under them — reassign first. A rename that
collides with a sibling is also 409.
 */
export const useGroupsRename = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof groupsRename>>, TError,{id: number;data: RenameGroupRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof groupsRename>>,
        TError,
        {id: number;data: RenameGroupRequest},
        TContext
      > => {
      return useMutation(getGroupsRenameMutationOptions(options), queryClient);
    }
