/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ErrorBody,
  HistoryDetail,
  HistoryEntry,
  HistoryListParams,
  UndoResponse
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type historyListResponse200 = {
  data: HistoryEntry[]
  status: 200
}

export type historyListResponse401 = {
  data: void
  status: 401
}

export type historyListResponse403 = {
  data: void
  status: 403
}

export type historyListResponseSuccess = (historyListResponse200) & {
  headers: Headers;
};
export type historyListResponseError = (historyListResponse401 | historyListResponse403) & {
  headers: Headers;
};

export type historyListResponse = (historyListResponseSuccess | historyListResponseError)

export const getHistoryListUrl = (params?: HistoryListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/history?${stringifiedParams}` : `/api/history`
}

/**
 * @summary GET /api/history[?limit=N] (viewer+) — the change log, newest first,
each with a human summary (§11.5).
 */
export const historyList = async (params?: HistoryListParams, options?: RequestInit): Promise<historyListResponse> => {

  const res = await fetch(getHistoryListUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: historyListResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as historyListResponse
}





export const getHistoryListQueryKey = (params?: HistoryListParams,) => {
    return [
    `/api/history`, ...(params ? [params] : [])
    ] as const;
    }


export const getHistoryListQueryOptions = <TData = Awaited<ReturnType<typeof historyList>>, TError = void>(params?: HistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyList>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHistoryListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof historyList>>> = ({ signal }) => historyList(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof historyList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HistoryListQueryResult = NonNullable<Awaited<ReturnType<typeof historyList>>>
export type HistoryListQueryError = void


export function useHistoryList<TData = Awaited<ReturnType<typeof historyList>>, TError = void>(
 params: undefined |  HistoryListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof historyList>>,
          TError,
          Awaited<ReturnType<typeof historyList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHistoryList<TData = Awaited<ReturnType<typeof historyList>>, TError = void>(
 params?: HistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof historyList>>,
          TError,
          Awaited<ReturnType<typeof historyList>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHistoryList<TData = Awaited<ReturnType<typeof historyList>>, TError = void>(
 params?: HistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/history[?limit=N] (viewer+) — the change log, newest first,
each with a human summary (§11.5).
 */

export function useHistoryList<TData = Awaited<ReturnType<typeof historyList>>, TError = void>(
 params?: HistoryListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyList>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHistoryListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type historyDetailResponse200 = {
  data: HistoryDetail
  status: 200
}

export type historyDetailResponse401 = {
  data: void
  status: 401
}

export type historyDetailResponse403 = {
  data: void
  status: 403
}

export type historyDetailResponse404 = {
  data: ErrorBody
  status: 404
}

export type historyDetailResponseSuccess = (historyDetailResponse200) & {
  headers: Headers;
};
export type historyDetailResponseError = (historyDetailResponse401 | historyDetailResponse403 | historyDetailResponse404) & {
  headers: Headers;
};

export type historyDetailResponse = (historyDetailResponseSuccess | historyDetailResponseError)

export const getHistoryDetailUrl = (id: number,) => {




  return `/api/history/${id}`
}

/**
 * @summary GET /api/history/{id} (viewer+) — the plain diff: changed apps +
scopes, never raw layer paths (§11.5).
 */
export const historyDetail = async (id: number, options?: RequestInit): Promise<historyDetailResponse> => {

  const res = await fetch(getHistoryDetailUrl(id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: historyDetailResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as historyDetailResponse
}





export const getHistoryDetailQueryKey = (id: number,) => {
    return [
    `/api/history/${id}`
    ] as const;
    }


export const getHistoryDetailQueryOptions = <TData = Awaited<ReturnType<typeof historyDetail>>, TError = void | ErrorBody>(id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyDetail>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHistoryDetailQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof historyDetail>>> = ({ signal }) => historyDetail(id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof historyDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type HistoryDetailQueryResult = NonNullable<Awaited<ReturnType<typeof historyDetail>>>
export type HistoryDetailQueryError = void | ErrorBody


export function useHistoryDetail<TData = Awaited<ReturnType<typeof historyDetail>>, TError = void | ErrorBody>(
 id: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof historyDetail>>,
          TError,
          Awaited<ReturnType<typeof historyDetail>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHistoryDetail<TData = Awaited<ReturnType<typeof historyDetail>>, TError = void | ErrorBody>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof historyDetail>>,
          TError,
          Awaited<ReturnType<typeof historyDetail>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useHistoryDetail<TData = Awaited<ReturnType<typeof historyDetail>>, TError = void | ErrorBody>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyDetail>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/history/{id} (viewer+) — the plain diff: changed apps +
scopes, never raw layer paths (§11.5).
 */

export function useHistoryDetail<TData = Awaited<ReturnType<typeof historyDetail>>, TError = void | ErrorBody>(
 id: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof historyDetail>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getHistoryDetailQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






export type undoResponse200 = {
  data: UndoResponse
  status: 200
}

export type undoResponse401 = {
  data: void
  status: 401
}

export type undoResponse403 = {
  data: void
  status: 403
}

export type undoResponse404 = {
  data: ErrorBody
  status: 404
}

export type undoResponse422 = {
  data: ErrorBody
  status: 422
}

export type undoResponseSuccess = (undoResponse200) & {
  headers: Headers;
};
export type undoResponseError = (undoResponse401 | undoResponse403 | undoResponse404 | undoResponse422) & {
  headers: Headers;
};

export type undoResponse = (undoResponseSuccess | undoResponseError)

export const getUndoUrl = (id: number,) => {




  return `/api/history/${id}/undo`
}

/**
 * @summary POST /api/history/{id}/undo (operator+) — author a NEW revision that
restores the whole tree to its content as of BEFORE change `{id}`
(§11.5 Undo). manifestVersion still only ever climbs (content may
revert; the version counter never does — §11.5 note). Only local
changes are undoable; upstream (synced) changes are refused.
 */
export const undo = async (id: number, options?: RequestInit): Promise<undoResponse> => {

  const res = await fetch(getUndoUrl(id),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: undoResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as undoResponse
}





export const getUndoMutationOptions = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undo>>, TError,{id: number}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof undo>>, TError,{id: number}, TContext> => {

const mutationKey = ['undo'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof undo>>, {id: number}> = (props) => {
          const {id} = props ?? {};

          return  undo(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UndoMutationResult = NonNullable<Awaited<ReturnType<typeof undo>>>

    export type UndoMutationError = void | ErrorBody

    /**
 * @summary POST /api/history/{id}/undo (operator+) — author a NEW revision that
restores the whole tree to its content as of BEFORE change `{id}`
(§11.5 Undo). manifestVersion still only ever climbs (content may
revert; the version counter never does — §11.5 note). Only local
changes are undoable; upstream (synced) changes are refused.
 */
export const useUndo = <TError = void | ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof undo>>, TError,{id: number}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof undo>>,
        TError,
        {id: number},
        TContext
      > => {
      return useMutation(getUndoMutationOptions(options), queryClient);
    }
