/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  EventsRouteParams
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type eventsRouteResponse200 = {
  data: string
  status: 200
}

export type eventsRouteResponse401 = {
  data: void
  status: 401
}

export type eventsRouteResponse403 = {
  data: void
  status: 403
}

export type eventsRouteResponseSuccess = (eventsRouteResponse200) & {
  headers: Headers;
};
export type eventsRouteResponseError = (eventsRouteResponse401 | eventsRouteResponse403) & {
  headers: Headers;
};

export type eventsRouteResponse = (eventsRouteResponseSuccess | eventsRouteResponseError)

export const getEventsRouteUrl = (params?: EventsRouteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reeve/v1/events?${stringifiedParams}` : `/api/reeve/v1/events`
}

/**
 * Event payload schemas (the rev-003/1 table, §6.3) are registered
 * as OpenAPI components by `openapi.rs` (D10: the UI's invalidation
 * handlers consume generated event types); the stream itself is SSE
 * (`event:` = type name, `data:` = the JSON payload, `id:` = the
 * per-stream monotonic id).
 * @summary GET /api/reeve/v1/events (§6.1) — viewer+.
 */
export const eventsRoute = async (params?: EventsRouteParams, options?: RequestInit): Promise<eventsRouteResponse> => {

  const res = await fetch(getEventsRouteUrl(params),
  {
    ...options,
    method: 'GET'


  }
)

  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: eventsRouteResponse['data'] = body ? (contentType.includes('json') ? JSON.parse(body) : body) : {}
  return { data, status: res.status, headers: res.headers } as eventsRouteResponse
}





export const getEventsRouteQueryKey = (params?: EventsRouteParams,) => {
    return [
    `/api/reeve/v1/events`, ...(params ? [params] : [])
    ] as const;
    }


export const getEventsRouteQueryOptions = <TData = Awaited<ReturnType<typeof eventsRoute>>, TError = void>(params?: EventsRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsRoute>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventsRouteQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventsRoute>>> = ({ signal }) => eventsRoute(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventsRoute>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type EventsRouteQueryResult = NonNullable<Awaited<ReturnType<typeof eventsRoute>>>
export type EventsRouteQueryError = void


export function useEventsRoute<TData = Awaited<ReturnType<typeof eventsRoute>>, TError = void>(
 params: undefined |  EventsRouteParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsRoute>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsRoute>>,
          TError,
          Awaited<ReturnType<typeof eventsRoute>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsRoute<TData = Awaited<ReturnType<typeof eventsRoute>>, TError = void>(
 params?: EventsRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsRoute>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof eventsRoute>>,
          TError,
          Awaited<ReturnType<typeof eventsRoute>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useEventsRoute<TData = Awaited<ReturnType<typeof eventsRoute>>, TError = void>(
 params?: EventsRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsRoute>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/reeve/v1/events (§6.1) — viewer+.
 */

export function useEventsRoute<TData = Awaited<ReturnType<typeof eventsRoute>>, TError = void>(
 params?: EventsRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof eventsRoute>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getEventsRouteQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






