/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  TerminalRouteParams
} from '../../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type terminalRouteResponse101 = {
  data: void
  status: 101
}

export type terminalRouteResponse401 = {
  data: void
  status: 401
}

export type terminalRouteResponse403 = {
  data: void
  status: 403
}

export type terminalRouteResponse404 = {
  data: void
  status: 404
}

export type terminalRouteResponse409 = {
  data: void
  status: 409
}

;
export type terminalRouteResponseError = (terminalRouteResponse101 | terminalRouteResponse401 | terminalRouteResponse403 | terminalRouteResponse404 | terminalRouteResponse409) & {
  headers: Headers;
};

export type terminalRouteResponse = (terminalRouteResponseError)

export const getTerminalRouteUrl = (deviceId: string,
    params?: TerminalRouteParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/reeve/v1/terminal/${deviceId}?${stringifiedParams}` : `/api/reeve/v1/terminal/${deviceId}`
}

/**
 * @summary GET /api/reeve/v1/terminal/{device_id} — the UI leg (§5.1),
operator-initiated (§5.3). Every denial is audited (§5.4) and
answered BEFORE upgrade.
 */
export const terminalRoute = async (deviceId: string,
    params?: TerminalRouteParams, options?: RequestInit): Promise<terminalRouteResponse> => {

  const res = await fetch(getTerminalRouteUrl(deviceId,params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: terminalRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as terminalRouteResponse
}





export const getTerminalRouteQueryKey = (deviceId: string,
    params?: TerminalRouteParams,) => {
    return [
    `/api/reeve/v1/terminal/${deviceId}`, ...(params ? [params] : [])
    ] as const;
    }


export const getTerminalRouteQueryOptions = <TData = Awaited<ReturnType<typeof terminalRoute>>, TError = void>(deviceId: string,
    params?: TerminalRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof terminalRoute>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getTerminalRouteQueryKey(deviceId,params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof terminalRoute>>> = ({ signal }) => terminalRoute(deviceId,params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: deviceId !== null && deviceId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof terminalRoute>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type TerminalRouteQueryResult = NonNullable<Awaited<ReturnType<typeof terminalRoute>>>
export type TerminalRouteQueryError = void


export function useTerminalRoute<TData = Awaited<ReturnType<typeof terminalRoute>>, TError = void>(
 deviceId: string,
    params: undefined |  TerminalRouteParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof terminalRoute>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof terminalRoute>>,
          TError,
          Awaited<ReturnType<typeof terminalRoute>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTerminalRoute<TData = Awaited<ReturnType<typeof terminalRoute>>, TError = void>(
 deviceId: string,
    params?: TerminalRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof terminalRoute>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof terminalRoute>>,
          TError,
          Awaited<ReturnType<typeof terminalRoute>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useTerminalRoute<TData = Awaited<ReturnType<typeof terminalRoute>>, TError = void>(
 deviceId: string,
    params?: TerminalRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof terminalRoute>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary GET /api/reeve/v1/terminal/{device_id} — the UI leg (§5.1),
operator-initiated (§5.3). Every denial is audited (§5.4) and
answered BEFORE upgrade.
 */

export function useTerminalRoute<TData = Awaited<ReturnType<typeof terminalRoute>>, TError = void>(
 deviceId: string,
    params?: TerminalRouteParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof terminalRoute>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getTerminalRouteQueryOptions(deviceId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}






