/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Per-app State Manifest entry. The agent diffs `secrets_version`
 * separately from the bundle digest: bundle unchanged +
 * `secrets_version` changed ⇒ re-resolve secrets and minimally
 * re-up, no bundle re-pull (spec/reeve/10-secrets.md §12;
 * docs/decisions/agent.md).
 */
export interface AppManifestEntry {
  /**
     * Application id (matches the rendered app dir /
     * `ApplicationDeployment.spec.applicationId`).
     */
  appId: string;
  /**
     * Deterministic deployment id of the rendered
     * `ApplicationDeployment` (docs/decisions/tree-render.md).
     * @nullable
     */
  deploymentId?: string | null;
  /**
     * Hash of resolved secret names+versions, never values
     * (spec/reeve/10-secrets.md §12; docs/decisions/delivery.md D13).
     * Spelled `secrets_version` on the wire — the exact token used
     * normatively throughout spec/reeve/.
     * @nullable
     */
  secrets_version?: string | null;
}
