/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { RevisionInfo } from './revision-info';

/**
 * One `GET /api/tree/blame/{*path}` entry: a revision at which the
 * path changed. `digest: null` marks a removal.
 */
export interface BlameEntry {
  /** @nullable */
  digest?: string | null;
  revision: RevisionInfo;
}
