/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Render-bundle reference — shaped after Margo's
 * `DeploymentBundleRef` (`workload-management-api-1.0.0.yaml`):
 * mediaType, digest, advisory sizeBytes, content-addressable url.
 */
export interface BundleRef {
  /**
     * `sha256:<hex>`; MUST be verified after pull — `sizeBytes` is
     * advisory only, never integrity.
     */
  digest: string;
  /** @nullable */
  mediaType?: string | null;
  /**
     * @minimum 0
     * @nullable
     */
  sizeBytes?: number | null;
  /**
     * Content-addressed pull URL (native OCI /v2 routes,
     * docs/decisions/delivery.md D7).
     */
  url: string;
}
