/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { CohortSpecLabels } from './cohort-spec-labels';

/**
 * Cohort selector (§11 terms): explicit device list, tree selections
 * (layer subtrees), and/or label matches (D12: labels select COHORTS
 * and filter UIs only — they never select or inject configuration).
 * Selectors union; the resolved cohort is recorded at creation.
 */
export interface CohortSpec {
  devices?: string[];
  /** All pairs must match the device's free-form labels. */
  labels?: CohortSpecLabels;
  /**
     * Layer dir names per D11 grammar (`00-fleet`, `05-class.<n>`,
     * `10-region.<n>`, `20-site.<n>`, `30-device.<id>`); the numeric
     * prefix is optional here (`site.plant-a` works).
     */
  layers?: string[];
}
