/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { I64 } from './i64';

/**
 * Commit outcome of both PUT endpoints (`changed: false` = identical
 * content, no new revision — D14 idempotence). Package PUTs also
 * carry validation `warnings`.
 */
export interface CommitResponse {
  changed: boolean;
  revision: I64;
  /** Always `local` — authoring only ever targets the local stream. */
  stream: string;
  /**
     * Package validation warnings (package PUTs only).
     * @nullable
     */
  warnings?: string[] | null;
}
