/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentState } from './deployment-state';
import type { StatusError } from './status-error';

/**
 * `components[]` entry (`deployment-status.md` "Component
 * Attributes"; `ComponentStatus` in
 * `workload-management-api-1.0.0.yaml`). MUST contain one entry per
 * component of the referenced `ApplicationDeployment`.
 */
export interface ComponentStatus {
  error?: null | StatusError;
  name: string;
  state: DeploymentState;
}
