/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `POST /api/tier-tokens` body: the raw tier token, shown once.
 */
export interface CreatedTierToken {
  name: string;
  site: string;
  syncPrefixes: string[];
  /** The raw tier token — only the hash is stored. */
  token: string;
}
