/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `POST /api/join-tokens` body: the raw token, shown exactly once.
 */
export interface CreatedJoinToken {
  /** @nullable */
  device_id?: string | null;
  expires_at: number;
  /** The raw join token (`rvj_<64 hex>`) — only the hash is stored. */
  join_token: string;
  max_uses: number;
  token_hash: string;
}
