/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { CohortSpec } from './cohort-spec';
import type { GateSpec } from './gate-spec';

/**
 * POST /api/rollouts body. Waves: exactly one of `waves` (explicit
 * partition), `strategy` (e.g. `["1", "10%", "rest"]`), `waveCount`,
 * or none (single wave = whole cohort).
 */
export interface CreateRequest {
  /**
     * Hold revision for not-yet-advanced devices; default: the target
     * revision's parent (see module docs — DECISION below).
     * @nullable
     */
  baselineRevision?: number | null;
  cohort: CohortSpec;
  /** @nullable */
  failureThreshold?: number | null;
  gate?: GateSpec;
  /** The source tree revision (§11.1) — an existing local revision. */
  revision: number;
  /** @nullable */
  strategy?: string[] | null;
  /**
     * @minimum 0
     * @nullable
     */
  waveCount?: number | null;
  /** @nullable */
  waves?: string[][] | null;
}
