/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Body of POST /api/tier-tokens.
 */
export interface CreateTierTokenRequest {
  /** Unique child-tier name (e.g. the gateway hostname). */
  name: string;
  /** The child's site label — the layer family it owns (§8.4). */
  site: string;
  /**
     * Tree-path prefixes the child may sync; default
     * [`DEFAULT_SYNC_PREFIXES`].
     * @nullable
     */
  syncPrefixes?: string[] | null;
  /**
     * Optional TTL; absent => non-expiring (revocation is the lever).
     * @nullable
     */
  ttlSecs?: number | null;
}
