/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

export interface CreateJoinTokenRequest {
  /**
     * Existing device to bind a re-enroll token to (D4).
     * @nullable
     */
  device_id?: string | null;
  /**
     * Default 1 (D4).
     * @nullable
     */
  max_uses?: number | null;
  /**
     * Seconds until expiry; default 86400 (24h, D4).
     * @nullable
     */
  ttl_secs?: number | null;
}
