/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { GroupKind } from './group-kind';

/**
 * `POST /api/groups` body: create a fleet (no parent) or a site (parent =
 * an existing fleet's id).
 */
export interface CreateGroupRequest {
  kind: GroupKind;
  name: string;
  /**
     * Required for a site (the containing fleet's id); MUST be absent for
     * a fleet.
     * @nullable
     */
  parentId?: number | null;
}
