/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `POST /api/rollouts` 201 body.
 */
export interface CreateRolloutResponse {
  /** Resolved cohort device ids. */
  cohort: string[];
  revision: number;
  /**
     * Present when this rollout is a rollback of another (§11.5).
     * @nullable
     */
  rollbackOf?: string | null;
  rolloutId: string;
  /** Human scope phrasing (§11.5: describe scope in words). */
  scopeDescription: string;
  /** Always `active` at creation. */
  state: string;
  /** The wave partition (device ids per wave). */
  waves: string[][];
}
