/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Optional tag cohort narrowing the scope (D12: tags select
 * cohorts, never configuration). All pairs must match a device's
 * tags for it to be included.
 * @nullable
 */
export type CreateRequestTagCohort = {[key: string]: string} | null;
