/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { ComponentStatus } from './component-status';
import type { DeploymentStatus } from './deployment-status';
import type { ReeveStatusExtension } from './reeve-status-extension';

/**
 * `DeploymentStatusManifest` request body
 * (`deployment-status.md` "Request Body Attributes"; posted to
 * `POST /api/v1/clients/{clientId}/deployments/{deploymentId}/status`).
 */
export interface DeploymentStatusManifest {
  apiVersion: string;
  components?: ComponentStatus[];
  /** UUID of the deployment specification, assigned by the WFM. */
  deploymentId: string;
  /**
     * Required only when reporting on behalf of a child device
     * (`deployment-status.md`); full hierarchy path when applicable.
     * @nullable
     */
  deviceId?: string | null;
  kind: string;
  reeve?: null | ReeveStatusExtension;
  status: DeploymentStatus;
}
