/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Deployment/component state
 * (`workload-management-api-1.0.0.yaml` `DeploymentStatusManifest.
 * status.state` enum; `deployment-status.md` "Status Attributes").
 */
export type DeploymentState = typeof DeploymentState[keyof typeof DeploymentState];


export const DeploymentState = {
  pending: 'pending',
  installing: 'installing',
  installed: 'installed',
  removing: 'removing',
  removed: 'removed',
  failed: 'failed',
} as const;
