/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response of both deploy and undeploy: the authoring outcome plus the
 * human framing (§11.5 — never a raw layer path).
 */
export interface DeployResponse {
  /** The deployed/undeployed app id. */
  app: string;
  /** `false` => identical content, no new revision (D14 idempotence). */
  changed: boolean;
  revision: number;
  /** Human scope phrasing, e.g. `Site plant-a` (§11.5). */
  scope: string;
}
