/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentState } from './deployment-state';
import type { StatusError } from './status-error';

/**
 * Overall deployment `status` (`deployment-status.md` "Status
 * Attributes"; an object, per the example manifest and the OpenAPI
 * schema — the attribute table's `[]status` type is contradicted by
 * both and is read as a spec typo).
 */
export interface DeploymentStatus {
  error?: null | StatusError;
  state: DeploymentState;
}
