/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeploymentState } from './deployment-state';

/**
 * `deployment-status` (§6.3): an ingested manifest changed a
 * deployment's overall state. `state` is the Margo enum
 * (`margo::status::DeploymentState`).
 */
export interface DeploymentStatusEvent {
  deploymentId: string;
  deviceId: string;
  state: DeploymentState;
  ts: string;
}
