/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Current state of one deployment on a device
 * (`deployment_status_current` row).
 */
export interface DeviceDeploymentState {
  deploymentId: string;
  /**
     * Device-assigned RFC 3339 timestamp (absent for vanilla reports).
     * @nullable
     */
  observedAt?: string | null;
  /** Server receipt time, unix seconds. */
  receivedAt: number;
  /**
     * Journal seq of the report (absent for vanilla Margo reports).
     * @nullable
     */
  seq?: number | null;
  /** Margo deployment state (`pending` … `failed`). */
  state: string;
}
