/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceDeploymentState } from './device-deployment-state';
import type { DeviceSummaryLabels } from './device-summary-labels';
import type { PresenceInfo } from './presence-info';

/**
 * One device as listed by `GET /api/devices`.
 */
export interface DeviceSummary {
  agentVersion: string;
  arch: string;
  /**
     * Layer-chain membership (D11: fleet -> class? -> region -> site
     * -> device), each nullable.
     * @nullable
     */
  class?: string | null;
  /** Current per-deployment states. */
  deployments: DeviceDeploymentState[];
  deviceId: string;
  /** Unix seconds. */
  enrolledAt: number;
  hostname: string;
  /**
     * Free-form labels (docs/decisions/tree-render.md D12: labels
     * group and filter, never configure).
     */
  labels: DeviceSummaryLabels;
  /**
     * Unix seconds of last contact; `null` = never seen.
     * @nullable
     */
  lastSeenAt?: number | null;
  presence: PresenceInfo;
  /** @nullable */
  region?: string | null;
  /** @nullable */
  site?: string | null;
  /**
     * Identity superseded by a newer enrollment from the same
     * hostname (docs/decisions/agent.md D4 wiped-box case).
     */
  stale: boolean;
  /**
     * Child tier this device reached us through (federation §8.3);
     * `null` = enrolled here.
     * @nullable
     */
  tierOrigin?: string | null;
}
