/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Free-form labels (docs/decisions/tree-render.md D12: labels
 * group and filter, never configure).
 */
export type DeviceSummaryLabels = {[key: string]: string};
