/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceSummary } from './device-summary';
import type { RenderProvenance } from './render-provenance';

/**
 * `GET /api/devices/{device_id}` response.
 */
export type DeviceDetail = DeviceSummary & ({
  render?: null | RenderProvenance;
});
