/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceClass } from './device-class';

export interface DeviceStatus {
  advanced: boolean;
  /** @nullable */
  advancedAt?: number | null;
  deviceId: string;
  status: DeviceClass;
  /**
     * D12/§11.1: render materially unchanged by the rollout — counts
     * as converged, surfaced so green never silently means "nothing
     * deployed here".
     */
  unaffected: boolean;
}
