/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One component's current state (Margo `ComponentStatus`), surfaced so
 * the UI can show which part of a deployment failed and why.
 */
export interface DeviceComponentState {
  /** @nullable */
  error?: string | null;
  name: string;
  state: string;
}
