/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Free-form key/value tags (spec/reeve/11-fleet-model.md §11.2) —
 * the same data as `labels`, under the fleet-model name the UI
 * uses. Ad-hoc grouping/filtering/rollout cohorts only; never
 * selects config (that is the layer chain's job).
 */
export type DeviceSummaryTags = {[key: string]: string};
