/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { PresenceState } from './presence-state';

/**
 * `device-presence` (§6.3): channel opens/drops.
 */
export interface DevicePresenceEvent {
  deviceId: string;
  /** RFC 3339 — since when the device has been in `state`. */
  since: string;
  state: PresenceState;
  ts: string;
}
