/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * §11.6 per-device rollout view: advanced / converged / healthy /
 * undetermined / failed. `Pending` = not yet advanced by its wave.
 */
export type DeviceClass = typeof DeviceClass[keyof typeof DeviceClass];


export const DeviceClass = {
  pending: 'pending',
  converged: 'converged',
  failed: 'failed',
  undetermined: 'undetermined',
} as const;
