/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One `GET /api/tree/diff/{a}/{b}` entry. `change` decides which
 * digests are present: `added` carries `new`, `removed` carries
 * `old`, `modified` carries both.
 */
export interface DiffEntry {
  /** `added` | `removed` | `modified`. */
  change: string;
  /** @nullable */
  new?: string | null;
  /** @nullable */
  old?: string | null;
  path: string;
}
