/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Disk usage/free for one filesystem (spec/reeve/05-health-journal.md
 * §7.2). Inner field names are reeve-chosen (the spec pins the
 * sample's semantics, not its sub-shape); extensible like the rest
 * of the sample.
 */
export interface DiskSample {
  /**
     * @minimum 0
     * @nullable
     */
  freeBytes?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  totalBytes?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  usedBytes?: number | null;
  [key: string]: unknown;
}
