/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { VerifySummary } from './verify-summary';

/**
 * The queryable status shape (§9.2 degraded flag, §9.3 upload lag,
 * §9.4 "last verified restore"). A deployment whose verify-restore
 * has never succeeded reads as having NO durability tier (§9.4) —
 * `effective_tier` encodes exactly that rule for the UI.
 */
export interface DurabilityStatus {
  degraded: boolean;
  /**
     * Current (last successfully shipped) snapshot generation.
     * @nullable
     */
  generation?: string | null;
  /** @nullable */
  last_changeset_at?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  last_changeset_seq?: number | null;
  /** @nullable */
  last_error?: string | null;
  /** @nullable */
  last_snapshot_at?: number | null;
  last_verify?: null | VerifySummary;
  /** @minimum 0 */
  pending_changesets: number;
  /** @nullable */
  snapshot_age_secs?: number | null;
  tier: string;
}
