/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DurabilityStatus } from './durability-status';

/**
 * `GET /api/durability/status` body: [`DurabilityStatus`] plus the
 * §9.4 `effective_tier` (an unverified tier reads as none).
 */
export type DurabilityStatusResponse = DurabilityStatus & ({
  /** `none` | `snapshot` | `changeset` | `none (unverified)`. */
  effective_tier: string;
  /**
     * Current server epoch (`settings.server_epoch`, spec/reeve/07-durability.md
     * §9.5): the high 16 bits of every manifestVersion. Restore fencing
     * increments it — the ops UI surfaces it next to durability posture.
     * @minimum 0
     */
  epoch: number;
});
