/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `durability-lag` (§6.3): changeset upload lag crossed/cleared a
 * threshold — ops dashboard signal (spec/reeve/07-durability.md
 * §9.3: changesets are keyed by generation id + monotonic seq).
 */
export interface DurabilityLagEvent {
  /**
     * Snapshot generation id (spec/reeve/07-durability.md §9.2 —
     * generation keys are string-shaped, e.g. `<rfc3339>-<schema>`).
     */
  generation: string;
  /** @minimum 0 */
  lagSeconds: number;
  /**
     * Last uploaded changeset sequence within the generation.
     * @minimum 0
     */
  lastSeq: number;
  ts: string;
}
