/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body of `POST /api/reeve/v1/enroll` (D4 step 1):
 * `{ join_token, hostname, arch, agent_version }`.
 */
export interface EnrollRequest {
  /** reeve-agent version performing the enrollment. */
  agent_version: string;
  /** Target architecture (e.g. `x86_64`, `aarch64`). */
  arch: string;
  /**
     * The enrolling box's hostname — the idempotency key for a retried
     * install with the same join token (D4).
     */
  hostname: string;
  /**
     * Operator-created join token (D4: TTL + max-uses, stored hashed
     * server-side). A re-enroll token is the same grammar, bound to an
     * existing device_id server-side.
     */
  join_token: string;
}
