/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response of `POST /api/reeve/v1/enroll` (D4 step 2): the issued
 * identity and the ONE device credential for every device-facing
 * surface (docs/decisions/auth.md D1).
 */
export interface EnrollResponse {
  /** Server-issued device identity. */
  device_id: string;
  /**
     * Enrollment-issued bearer token (`rvd_<64 hex>`). Shown exactly
     * once; the server keeps only its hash.
     */
  device_token: string;
  /**
     * True when this enrollment resumed an existing device identity
     * (idempotent re-run of the same join token + hostname, or a
     * re-enroll token bound to an existing device — D4).
     */
  resumed?: boolean;
}
