/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The one error-body shape every JSON error response uses:
 * `{ "error": "<human-readable message>" }`. Schema component for the
 * D10 openapi.json (docs/decisions/ui.md); handlers keep building the
 * body via `json!` — this type documents the contract.
 */
export interface ErrorBody {
  error: string;
}
