/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

export type EventsRouteParams = {
/**
 * Comma-separated event-type filter (§6.1); unknown names ignored. Types: reset, device-presence, deployment-status, terminal-session, health-state, verify-restore, durability-lag, rollout, secret-rotation, federation-sync
 */
types?: string;
};
