/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `GET /api/federation/status` body. `mode` decides which fields are
 * present: `gateway` carries the upstream/sync bookkeeping, `root`
 * only `childTiers` and `upstreamOriginHead`.
 */
export interface FederationStatus {
  /** Active (non-revoked) child tier tokens. */
  childTiers: number;
  /** @nullable */
  forwardedSeqTotal?: number | null;
  /** @nullable */
  lastSyncAt?: number | null;
  /** @nullable */
  lastSyncError?: string | null;
  /** `root` | `gateway`. */
  mode: string;
  /** @nullable */
  site?: string | null;
  /** @nullable */
  syncIntervalSecs?: number | null;
  /** @nullable */
  upstream?: string | null;
  /**
     * Local row id of the upstream head.
     * @nullable
     */
  upstreamLocalRow?: number | null;
  /**
     * Parent-tier revision id of the synced upstream head.
     * @nullable
     */
  upstreamOriginHead?: number | null;
}
