/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Federation sync outcome (`federation-sync` payload;
 * spec/reeve/06-federation.md §8.2 — sync state is queryable AND
 * evented; an id/digest divergence is surfaced here too, never
 * auto-resolved). Additive to the rev-003/1 table: unknown event
 * types are ignored by older clients (§6.3).
 */
export interface FederationSyncEvent {
  /**
     * Revisions appended by this tick.
     * @minimum 0
     */
  appended: number;
  /** @nullable */
  error?: string | null;
  ok: boolean;
  /**
     * Parent-tier revision id of the synced upstream head, when known.
     * @minimum 0
     * @nullable
     */
  originHead?: number | null;
  ts: string;
  /** The parent tier URL this gateway syncs from. */
  upstream: string;
}
