/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Gate policy overrides (§11.3); defaults above.
 */
export interface GateSpec {
  /** @nullable */
  gateTimeoutSecs?: number | null;
  /** @nullable */
  passFraction?: number | null;
  /** @nullable */
  soakSecs?: number | null;
  /**
     * Max undetermined devices a passing gate tolerates. Absent =
     * the whole wave may be undetermined (chronically-offline fleets,
     * Law 5); 0 = strict.
     * @nullable
     */
  undeterminedAllowance?: number | null;
}
