/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { GroupKind } from './group-kind';

/**
 * A single created/renamed group.
 */
export interface GroupNode {
  id: number;
  kind: GroupKind;
  name: string;
  /**
     * The parent fleet's id for a site; `null` for a fleet.
     * @nullable
     */
  parentId?: number | null;
}
