/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { FleetNode } from './fleet-node';

/**
 * `GET /api/groups` body: the fleet->site containment tree. A scoped
 * read (`?fleet=<name>`) returns the same shape with only that fleet's
 * subtree in `fleets`.
 */
export interface GroupTree {
  fleets: FleetNode[];
}
