/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A group kind (§11.1): only fleet and site are contained groups.
 */
export type GroupKind = typeof GroupKind[keyof typeof GroupKind];


export const GroupKind = {
  fleet: 'fleet',
  site: 'site',
} as const;
