/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * What is degraded (spec/reeve/05-health-journal.md §7.4):
 * `Device` — the device itself breaches thresholds; `Link` — the
 * path was down but backfill shows the device was fine.
 */
export type HealthKind = typeof HealthKind[keyof typeof HealthKind];


export const HealthKind = {
  device: 'device',
  link: 'link',
} as const;
