/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Server-side health classification
 * (spec/reeve/05-health-journal.md §7.4). `Unknown` (offline window
 * not yet backfilled) MUST be surfaced as unknown, never silently
 * assumed healthy or dead.
 */
export type HealthState = typeof HealthState[keyof typeof HealthState];


export const HealthState = {
  healthy: 'healthy',
  degraded: 'degraded',
  unknown: 'unknown',
} as const;
