/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { HealthKind } from './health-kind';
import type { HealthState } from './health-state';

/**
 * `health-state` (§6.3): health classification changed
 * (spec/reeve/05-health-journal.md §7.4).
 */
export interface HealthStateEvent {
  deviceId: string;
  kind: HealthKind;
  state: HealthState;
  ts: string;
}
