/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DiskSample } from './disk-sample';

/**
 * Per-filesystem usage, keyed by mount point / identifier.
 * @nullable
 */
export type HealthSampleDisk = {[key: string]: DiskSample} | null;
