/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { HealthSampleDisk } from './health-sample-disk';
import type { HealthSampleRestarts } from './health-sample-restarts';
import type { MemorySample } from './memory-sample';

/**
 * A point-in-time health sample (spec/reeve/05-health-journal.md
 * §7.2): disk usage/free per relevant filesystem, memory usage,
 * load averages, per-workload container restart counts, agent
 * version, clock skew vs the server. "Fields are extensible;
 * receivers MUST ignore unknown sample fields" — unknown fields are
 * captured (and re-emitted) via `extra`.
 */
export interface HealthSample {
  /** @nullable */
  agentVersion?: string | null;
  /**
     * Clock skew versus the server in milliseconds, measured
     * opportunistically when connected (§7.2 — skew matters because
     * original timestamps are device-assigned).
     * @nullable
     */
  clockSkewMs?: number | null;
  /**
     * Per-filesystem usage, keyed by mount point / identifier.
     * @nullable
     */
  disk?: HealthSampleDisk;
  /**
     * Load averages (1/5/15 min).
     * @nullable
     */
  load?: number[] | null;
  memory?: null | MemorySample;
  /**
     * Per-workload container restart counts, from the active
     * Provider.
     * @nullable
     */
  restarts?: HealthSampleRestarts;
  [key: string]: unknown;
}
