/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { Scope } from './scope';

/**
 * One changed app+scope in a [`HistoryDetail`] (never a raw path).
 */
export interface HistoryChange {
  /** The app id. */
  app: string;
  /** `deployed` | `undeployed` | `changed`. */
  change: string;
  /** The scope the change touched. */
  scope: Scope;
  /** Human scope phrasing (`Site plant-a`). */
  scopeLabel: string;
}
