/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { HistoryChange } from './history-change';

/**
 * `GET /api/history/{id}` body: the plain, path-free diff (§11.5).
 */
export interface HistoryDetail {
  /**
     * Changed apps + scopes. Empty when the change touched only
     * non-app content (a vendored package) — see `otherChanges`.
     */
  changes: HistoryChange[];
  id: number;
  /**
     * Count of changed tree paths outside any `apps/<app>/` (package
     * vendoring, etc.) — surfaced as a number, never as paths.
     * @minimum 0
     */
  otherChanges: number;
  summary: string;
  when: string;
  who: string;
}
