/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One `GET /api/history` entry (§11.5: who/what/when, no plumbing).
 */
export interface HistoryEntry {
  /**
     * Opaque change id (the revision id under the hood, but the UI
     * treats it as a change handle — §11.5).
     */
  id: number;
  /**
     * Human one-liner, e.g. `deployed nginx to Site plant-a`, else
     * `config change`.
     */
  summary: string;
  /** RFC 3339 timestamp. */
  when: string;
  /** The author of the change. */
  who: string;
}
