/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One join token row, as listed to operators (never the raw token).
 */
export interface JoinTokenInfo {
  created_at: number;
  created_by: string;
  /**
     * Set => re-enroll token bound to this existing device (D4).
     * @nullable
     */
  device_id?: string | null;
  expires_at: number;
  max_uses: number;
  /** @nullable */
  revoked_at?: number | null;
  token_hash: string;
  uses: number;
}
