/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { JournalRecord } from './journal-record';

/**
 * Request body of `POST /api/reeve/v1/journal/{deviceId}`
 * (spec/reeve/05-health-journal.md §7.3): unacknowledged records in
 * batches ordered by sequence number.
 */
export interface JournalBatch {
  records?: JournalRecord[];
}
