/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { JournalRecordKind } from './journal-record-kind';

/**
 * One journal record in a backfill batch
 * (spec/reeve/05-health-journal.md §7.3 backfill path). Idempotency
 * key is `(deviceId, seq)` — deviceId travels in the endpoint path.
 */
export interface JournalRecord {
  kind: JournalRecordKind;
  /** Original timestamp (RFC 3339), assigned when journaled. */
  observedAt: string;
  /**
     * The journaled payload: a full `DeploymentStatusManifest` for
     * `status`, a [`HealthSample`] for `health`, a free-form object
     * for `lifecycle`, absent for `gap`.
     */
  payload?: unknown;
  /**
     * Monotonic per-device sequence number (§7.1).
     * @minimum 0
     */
  seq: number;
}
