/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One status-journal record (spec/reeve/05-health-journal.md §7.3).
 */
export interface JournalEntry {
  /** `status` | `health` | `lifecycle` | `gap`. */
  kind: string;
  /** Device-assigned original RFC 3339 timestamp, verbatim. */
  observedAt: string;
  /** The journaled payload; absent for gap marks. */
  payload?: unknown;
  /** Server receipt time, unix seconds. */
  receivedAt: number;
  seq: number;
}
