/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Response: "the server replies with the highest contiguously
 * ingested sequence number; that acknowledgement is what permits
 * journal eviction" (spec/reeve/05-health-journal.md §7.3).
 */
export interface JournalAck {
  /** @minimum 0 */
  ackedSeq: number;
}
