/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { JournalEntry } from './journal-entry';

/**
 * `GET /api/devices/{device_id}/journal` response: newest first.
 */
export interface JournalPage {
  /**
     * Pass as `before_seq` to fetch the next (older) page; absent
     * when this page reached the start of the journal.
     * @nullable
     */
  nextBeforeSeq?: number | null;
  records: JournalEntry[];
}
