/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Kind of a journal record (spec/reeve/05-health-journal.md §7.1):
 * status reports, health samples, agent lifecycle marks (start,
 * converge begin/end, provider errors), and gap marks (forced
 * eviction of unacknowledged records — so the server can
 * distinguish "evicted" from "never happened").
 */
export type JournalRecordKind = typeof JournalRecordKind[keyof typeof JournalRecordKind];


export const JournalRecordKind = {
  status: 'status',
  health: 'health',
  lifecycle: 'lifecycle',
  gap: 'gap',
} as const;
