/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

export type ListRevisionsParams = {
/**
 * Max revisions returned; default 100, cap 1000
 * @minimum 0
 */
limit?: number;
};
