/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `manifestVersion` — logically the pair `(epoch, counter)` compared
 * lexicographically, encoded on the wire as ONE monotonically
 * increasing unsigned 64-bit integer: epoch in the high 16 bits,
 * counter in the low 48 (spec/reeve/08-packaging.md §10.2). Plain
 * integer comparison IS the pair comparison, and the wire value
 * stays exactly Margo's modeled shape (`ManifestVersion`: monotonic
 * u64 in `[1, 2^64-1]`, `workload-management-api-1.0.0.yaml` —
 * "The first manifest MUST use 1").
 *
 * Agent rules (§10.2): a non-increasing value is rejected and logged
 * as a SECURITY event; an increase that bumps the epoch bits is
 * accepted and logged as a NOTABLE event (a restore happened,
 * spec/reeve/07-durability.md §9.5 restore fencing).
 * @minimum 0
 */
export type ManifestVersion = number;
