/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Memory usage (spec/reeve/05-health-journal.md §7.2).
 */
export interface MemorySample {
  /**
     * @minimum 0
     * @nullable
     */
  totalBytes?: number | null;
  /**
     * @minimum 0
     * @nullable
     */
  usedBytes?: number | null;
  [key: string]: unknown;
}
