/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { PatchDeviceRequestTags } from './patch-device-request-tags';

/**
 * `PATCH /api/devices/{device_id}` body: a partial device update
 * (spec/reeve/11-fleet-model.md §11.3). Every field is optional;
 * `null` clears an assignment/rename, an absent field is unchanged.
 */
export interface PatchDeviceRequest {
  /**
     * Human rename; `null` clears it (falls back to hostname).
     * @nullable
     */
  displayName?: string | null;
  /**
     * Hierarchy assignment; `null` unassigns (removes the layer from
     * the chain). A change re-renders the device.
     * @nullable
     */
  fleet?: string | null;
  /**
     * Pin hold (§11.3). Needs no re-render (the device holds where it
     * is; unpinning is picked up on the next poll).
     * @nullable
     */
  pinned?: boolean | null;
  /** @nullable */
  site?: string | null;
  /**
     * Replace the free-form tag set (§11.2). `null` clears all tags.
     * @nullable
     */
  tags?: PatchDeviceRequestTags;
  /** @nullable */
  type?: string | null;
}
