/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { PresenceState } from './presence-state';

/**
 * Presence answer (spec/reeve/02-channel.md §4.3 vocabulary).
 */
export interface PresenceInfo {
  /**
     * Unix seconds: channel-open time when online via channel,
     * last contact otherwise; `null` = never seen.
     * @nullable
     */
  since?: number | null;
  /** `online` | `offline`. */
  state: PresenceState;
}
