/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Device presence state (`device-presence` payload, §6.3;
 * spec/reeve/02-channel.md §4.3).
 */
export type PresenceState = typeof PresenceState[keyof typeof PresenceState];


export const PresenceState = {
  online: 'online',
  offline: 'offline',
} as const;
