/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { PutFilesRequestFiles } from './put-files-request-files';

/**
 * Body of both PUT endpoints: the complete content of one layer (or
 * package) as relative path -> base64(content). Base64 keeps the wire
 * JSON binary-safe (compose files are text, but package resources —
 * icons — are not).
 */
export interface PutFilesRequest {
  /** Relative path within the layer/package -> standard-base64 bytes. */
  files: PutFilesRequestFiles;
  /**
     * Commit message; a default is derived when absent.
     * @nullable
     */
  message?: string | null;
}
