/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Body of PUT /api/secrets. `value` is plaintext in RAM only — it is
 * sealed before touching the DB and never echoed back or logged.
 */
export interface PutSecretRequest {
  name: string;
  scope: string;
  value: string;
}
