/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { HealthSample } from './health-sample';

/**
 * The additive `reeve` object on a `DeploymentStatusManifest`
 * (spec/reeve/05-health-journal.md §7.3, rev-001 example):
 *
 * ```json
 * "reeve": { "observedAt": "2026-07-10T06:12:03Z", "seq": 48211,
 *            "health": { "...": "..." } }
 * ```
 *
 * The server uses `observedAt`/`seq` to place the report in history
 * and detect records it already holds. A vanilla WFM ignores the
 * whole object (spec/reeve/01-framework.md §3.7 audit row REV-004).
 */
export interface ReeveStatusExtension {
  health?: null | HealthSample;
  /**
     * Original timestamp (RFC 3339) — assigned when journaled on
     * the device, never rewritten (§7 "original timestamp").
     */
  observedAt: string;
  /**
     * Monotonic per-device sequence number (§7.1).
     * @minimum 0
     */
  seq: number;
}
