/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { RenderFailure } from './render-failure';

/**
 * `POST /api/render` body: the render pass report.
 */
export interface RenderKickResponse {
  failed: RenderFailure[];
  /**
     * Devices whose manifest changed (and was bumped).
     * @minimum 0
     */
  rendered: number;
  /**
     * Devices already current (no bump — D3).
     * @minimum 0
     */
  unchanged: number;
}
