/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { AppManifestEntry } from './app-manifest-entry';

/**
 * Render provenance of a device's current State Manifest
 * (`device_manifests` row + the manifest's per-app entries;
 * docs/decisions/delivery.md D13).
 */
export interface RenderProvenance {
  /**
     * Per-app manifest entries — carries each app's `secrets_version`
     * (spec/reeve/10-secrets.md §12.4).
     */
  apps: AppManifestEntry[];
  /**
     * OCI image manifest digest the device pulls; `null` = zero apps.
     * @nullable
     */
  bundleDigest?: string | null;
  /** sha256 over the rendered apps/** file set (change detector). */
  contentDigest: string;
  /**
     * Low 48 bits — monotonic per device.
     * @minimum 0
     */
  counter: number;
  /**
     * High 16 bits — bumped by restore fencing
     * (spec/reeve/07-durability.md §9.5).
     * @minimum 0
     */
  epoch: number;
  /** Strong ETag of the served manifest JSON. */
  etag: string;
  /** D2 render generation counter. */
  generation: number;
  /**
     * The packed (epoch, counter) wire u64
     * (spec/reeve/08-packaging.md §10.2).
     * @minimum 0
     */
  manifestVersion: number;
  /** Local-stream revision id this device was last rendered against. */
  renderedRevision: number;
  /** Unix seconds. */
  updatedAt: number;
}
