/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `reset` (§6.2): replay from `Last-Event-ID` not possible; the
 * client MUST treat all cached state as stale and refetch.
 */
export interface ResetEvent {
  ts: string;
}
