/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One resolved secret: plaintext value + its version (the rotation
 * counter that feeds the manifest-level `secrets_version` hash,
 * spec/reeve/10-secrets.md §12.4).
 */
export interface ResolvedSecret {
  /** Plaintext. RAM/TLS/env-file only (§12.3); never log. */
  value: string;
  /**
     * Version at resolution time — audit metadata, safe to log.
     * @minimum 0
     */
  version: number;
}
