/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { I64 } from './i64';

/**
 * Revision metadata as served to clients.
 */
export interface RevisionInfo {
  author: string;
  /** RFC 3339. */
  created_at: string;
  id: I64;
  message: string;
  parent?: null | I64;
  /** `local` | `upstream` (two-stream federation, D13). */
  stream: string;
}
