/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { RevisionDetailFiles } from './revision-detail-files';
import type { RevisionInfo } from './revision-info';

/**
 * `GET /api/tree/revisions/{id}` body.
 */
export interface RevisionDetail {
  /** Full manifest at that revision: tree path -> blob digest. */
  files: RevisionDetailFiles;
  revision: RevisionInfo;
}
