/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Human role (docs/decisions/auth.md D1): admin | operator | viewer.
 *
 * Ordered so `Viewer < Operator < Admin`; "at least operator" is
 * `role >= Role::Operator`.
 */
export type Role = typeof Role[keyof typeof Role];


export const Role = {
  viewer: 'viewer',
  operator: 'operator',
  admin: 'admin',
} as const;
