/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { RolloutPhase } from './rollout-phase';

/**
 * `rollout` (§6.3): rollout/wave transition.
 */
export interface RolloutEvent {
  phase: RolloutPhase;
  rolloutId: string;
  ts: string;
  /**
     * Wave index within the rollout's ordered wave list
     * (spec/reeve/09-rollouts.md).
     * @minimum 0
     */
  wave: number;
}
