/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Rollout/wave phase (`rollout` payload, §6.3;
 * spec/reeve/09-rollouts.md §11.6).
 */
export type RolloutPhase = typeof RolloutPhase[keyof typeof RolloutPhase];


export const RolloutPhase = {
  started: 'started',
  gated: 'gated',
  paused: 'paused',
  completed: 'completed',
  failed: 'failed',
} as const;
