/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One `GET /api/rollouts` entry.
 */
export interface RolloutSummary {
  createdAt: number;
  createdBy: string;
  currentWave: number;
  deviceCount: number;
  /** @nullable */
  pauseReason?: string | null;
  revision: number;
  rolloutId: string;
  /** Human scope phrasing (§11.5), e.g. `Site plant-a tagged env=prod`. */
  scopeDescription: string;
  /** `active` | `paused` | `aborted` | `completed`. */
  state: string;
  updatedAt: number;
  waveCount: number;
}
