/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { GatePolicy } from './gate-policy';
import type { RolloutDetailCohort } from './rollout-detail-cohort';
import type { TransitionEntry } from './transition-entry';
import type { WaveStatus } from './wave-status';

/**
 * `GET /api/rollouts/{rollout_id}` body (§11.6 full status).
 */
export interface RolloutDetail {
  /** The cohort spec as recorded at creation. */
  cohort: RolloutDetailCohort;
  createdAt: number;
  createdBy: string;
  currentWave: number;
  failureThreshold: number;
  gate: GatePolicy;
  /** @nullable */
  pauseReason?: string | null;
  /** §11.1 MUST: devices whose render the rollout does not change. */
  pinnedUnaffected: number;
  revision: number;
  rolloutId: string;
  state: string;
  transitions: TransitionEntry[];
  updatedAt: number;
  waves: WaveStatus[];
}
