/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * A deploy/rollout target (§11.4). `kind` is the JSON discriminator:
 * `{"kind":"all"}`, `{"kind":"fleet","name":"north"}`, …,
 * `{"kind":"devices","ids":["dev-1","dev-2"]}`.
 */
export type Scope = {
  kind: 'all';
} | {
  kind: 'fleet';
  name: string;
} | {
  kind: 'site';
  name: string;
} | {
  kind: 'type';
  name: string;
} | {
  ids: string[];
  kind: 'devices';
};
