/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { SecretRotationState } from './secret-rotation-state';

/**
 * `secret-rotation` (§6.3): a secret version changed / all affected
 * devices report converged. Carries metadata only, never values
 * (§6.4; spec/reeve/10-secrets.md).
 */
export interface SecretRotationEvent {
  scope: string;
  secretName: string;
  state: SecretRotationState;
  ts: string;
  /**
     * Secret version (bumped on rotation, spec/reeve/10-secrets.md).
     * @minimum 0
     */
  version: number;
}
