/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Secret rotation propagation state (`secret-rotation` payload,
 * §6.3; spec/reeve/10-secrets.md §12).
 */
export type SecretRotationState = typeof SecretRotationState[keyof typeof SecretRotationState];


export const SecretRotationState = {
  propagating: 'propagating',
  converged: 'converged',
} as const;
