/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { SecretsResolveResponseSecrets } from './secrets-resolve-response-secrets';

/**
 * Response body: resolutions keyed by requested name. A name the
 * device may not read — or that does not exist — is simply ABSENT
 * (indistinguishable by design: the resolve endpoint must not be a
 * secret-existence oracle beyond the device's own scope, §12.6).
 */
export interface SecretsResolveResponse {
  secrets: SecretsResolveResponseSecrets;
}
