/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One secret's METADATA — the only readable surface after entry
 * (§12.2 write-only: name, scope, version, timestamps; never values).
 */
export interface SecretInfo {
  created_at: number;
  name: string;
  /** @nullable */
  rotated_at?: number | null;
  scope: string;
  /** @minimum 0 */
  version: number;
}
