/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `PUT /api/secrets` body: metadata of the written secret — never
 * the value (§12.2 write-only).
 */
export interface SecretWritten {
  name: string;
  scope: string;
  /**
     * Version after the write (bumped on rotation).
     * @minimum 0
     */
  version: number;
}
