/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Request body: the secret names referenced (`${secret:<name>}`)
 * by the requesting device's rendered apps. Names only — never
 * values; names are metadata (spec/reeve/10-secrets.md §12.6
 * "who resolved what version when — metadata, not values").
 */
export interface SecretsResolveRequest {
  secrets: string[];
}
