/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { ServerCapabilities } from './server-capabilities';

/**
 * `GET /api/server` body: capability advertisement plus this
 * instance's declared topology tier (spec/reeve/11-fleet-model.md
 * §11.6) for the UI.
 */
export type ServerInfo = ServerCapabilities & ({
  /**
     * The site label this instance serves; `null` on a root tier.
     * @nullable
     */
  site?: string | null;
  /** `root` (the cloud/hub) or `site` (an on-prem gateway), §11.6. */
  tier: string;
  /**
     * Present iff this instance syncs from a parent tier
     * (`REEVE_UPSTREAM` set) — the operative federation signal (D9).
     */
  upstream: boolean;
});
