/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The server-side advertisement at
 * `GET /api/reeve/v1/capabilities` — "its extension list plus
 * server version" (spec/reeve/01-framework.md §3.3). 404 or any
 * error means "vanilla Margo server"; the agent proceeds with pure
 * Margo behavior.
 */
export interface ServerCapabilities {
  /** Same `"rev-NNN/V"` grammar as the agent side. */
  extensions?: string[];
  serverVersion: string;
}
