/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One site under a fleet in the [`GroupTree`].
 */
export interface SiteNode {
  id: number;
  name: string;
}
