/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * The stack to deploy: a vendored package (`packages/<package>/
 * <version>/`, D11) and an optional deployment profile. `name` is the
 * app's dir under the scope layer (`apps/<name>/`) — defaults to the
 * package name, so `{package, version}` is the minimal stack.
 */
export interface StackRef {
  /**
     * App id in the layer (`apps/<name>/`). Absent => the package name.
     * @nullable
     */
  name?: string | null;
  /** Vendored package name (`packages/<package>/`). */
  package: string;
  /**
     * Deployment profile id (Margo `deploymentProfiles[].id`); absent =>
     * the package's sole/only-compose profile is selected at render.
     * @nullable
     */
  profile?: string | null;
  /** Vendored package version. */
  version: string;
}
