/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { AppManifestEntry } from './app-manifest-entry';
import type { BundleRef } from './bundle-ref';
import type { ManifestVersion } from './manifest-version';

/**
 * The reeve State Manifest body returned by
 * `GET /api/reeve/v1/manifest` (spec/reeve/08-packaging.md §10.2) —
 * State-Manifest-shaped after Margo's `UnsignedAppStateManifest`
 * (`workload-management-api-1.0.0.yaml`): `manifestVersion`,
 * render-bundle digest + pull URL, per-app `secrets_version`.
 */
export interface StateManifest {
  /**
     * Per-app entries carrying `secrets_version`
     * (docs/decisions/delivery.md D13; spec/reeve/10-secrets.md §12).
     */
  apps?: AppManifestEntry[];
  bundle?: null | BundleRef;
  manifestVersion: ManifestVersion;
}
