/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `error` element (`deployment-status.md` "Error Attributes").
 * Reserved gateway-generated codes: 101 unknown child device, 102
 * child device unreachable, 103 autonomous placement not supported.
 */
export interface StatusError {
  /** @nullable */
  code?: string | null;
  /** @nullable */
  message?: string | null;
  /**
     * Device id (full hierarchy) or component/deployment name that
     * generated the error (`deployment-status.md`).
     * @nullable
     */
  source?: string | null;
}
