/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Terminal session lifecycle phase (`terminal-session` payload,
 * §6.3; spec/reeve/03-terminal.md §5.4).
 */
export type TerminalPhase = typeof TerminalPhase[keyof typeof TerminalPhase];


export const TerminalPhase = {
  requested: 'requested',
  opened: 'opened',
  closed: 'closed',
  denied: 'denied',
} as const;
