/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * One `GET /api/tier-tokens` entry (metadata, never raw tokens).
 */
export interface TierTokenInfo {
  createdAt: number;
  createdBy: string;
  /** @nullable */
  expiresAt?: number | null;
  name: string;
  /** @nullable */
  revokedAt?: number | null;
  site: string;
  syncPrefixes: string[];
}
