/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * `POST /api/history/{id}/undo` body.
 */
export interface UndoResponse {
  /** `false` => nothing to undo (content already matched). */
  changed: boolean;
  /**
     * The change id the content was restored to (before the undone
     * change); `null` when the undone change was the first.
     * @nullable
     */
  restoredTo?: number | null;
  /** The new change id that restored prior content. */
  revision: number;
}
