/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Outcome of a verify-restore run (`verify-restore` payload, §6.3;
 * spec/reeve/07-durability.md §9.4).
 */
export type VerifyRestoreOutcome = typeof VerifyRestoreOutcome[keyof typeof VerifyRestoreOutcome];


export const VerifyRestoreOutcome = {
  ok: 'ok',
  failed: 'failed',
} as const;
