/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { VerifyRestoreOutcome } from './verify-restore-outcome';

/**
 * `verify-restore` (§6.3): a verify-restore run completed.
 */
export interface VerifyRestoreEvent {
  /** @nullable */
  detail?: string | null;
  outcome: VerifyRestoreOutcome;
  /** RFC 3339 timestamp of the snapshot that was verified. */
  snapshotTs: string;
  ts: string;
}
