/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */

/**
 * Latest recorded run, for the status surface ("last verified
 * restore: <when>", §9.4).
 */
export interface VerifySummary {
  /** @nullable */
  detail?: string | null;
  finished_at: number;
  /** @nullable */
  generation?: string | null;
  /** @nullable */
  last_seq?: number | null;
  outcome: string;
}
