/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { DeviceStatus } from './device-status';
import type { WaveCounts } from './wave-counts';
import type { WaveStatusGate } from './wave-status-gate';

/**
 * One wave in a [`RolloutDetail`].
 */
export interface WaveStatus {
  counts: WaveCounts;
  devices: DeviceStatus[];
  /** Recorded gate evaluation (free-form; §11.3). */
  gate: WaveStatusGate;
  /** @nullable */
  gatedAt?: number | null;
  index: number;
  /** @nullable */
  soakStartedAt?: number | null;
  /** `pending` | `advancing` | `soaking` | `passed` | `failed`. */
  state: string;
}
