/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import type { Role } from './role';

/**
 * `GET /api/auth/me` body. `kind` decides which identity fields are
 * present: `human` carries `user`+`role`, `device` carries
 * `deviceId`, `anonymous` carries neither.
 */
export interface WhoAmI {
  /** @nullable */
  deviceId?: string | null;
  effectiveRole?: null | Role;
  /** `human` | `device` | `anonymous`. */
  kind: string;
  role?: null | Role;
  /** @nullable */
  user?: string | null;
}
