/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * reeve
 * Fleet desired-state manager (Margo-inspired). Human API consumed by the reeve UI, plus the device-facing wire surface.
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  EnrollRequest,
  EnrollResponse,
  ErrorBody
} from '../../model';





export type enrollRouteResponse200 = {
  data: EnrollResponse
  status: 200
}

export type enrollRouteResponse401 = {
  data: ErrorBody
  status: 401
}

export type enrollRouteResponse422 = {
  data: ErrorBody
  status: 422
}

export type enrollRouteResponse500 = {
  data: ErrorBody
  status: 500
}

export type enrollRouteResponseSuccess = (enrollRouteResponse200) & {
  headers: Headers;
};
export type enrollRouteResponseError = (enrollRouteResponse401 | enrollRouteResponse422 | enrollRouteResponse500) & {
  headers: Headers;
};

export type enrollRouteResponse = (enrollRouteResponseSuccess | enrollRouteResponseError)

export const getEnrollRouteUrl = () => {




  return `/api/reeve/v1/enroll`
}

/**
 * @summary POST /api/reeve/v1/enroll (D4 step 1-2).
 */
export const enrollRoute = async (enrollRequest: EnrollRequest, options?: RequestInit): Promise<enrollRouteResponse> => {

  const res = await fetch(getEnrollRouteUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(enrollRequest)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: enrollRouteResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as enrollRouteResponse
}





export const getEnrollRouteMutationOptions = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enrollRoute>>, TError,{data: EnrollRequest}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof enrollRoute>>, TError,{data: EnrollRequest}, TContext> => {

const mutationKey = ['enrollRoute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof enrollRoute>>, {data: EnrollRequest}> = (props) => {
          const {data} = props ?? {};

          return  enrollRoute(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type EnrollRouteMutationResult = NonNullable<Awaited<ReturnType<typeof enrollRoute>>>
    export type EnrollRouteMutationBody = EnrollRequest
    export type EnrollRouteMutationError = ErrorBody

    /**
 * @summary POST /api/reeve/v1/enroll (D4 step 1-2).
 */
export const useEnrollRoute = <TError = ErrorBody,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof enrollRoute>>, TError,{data: EnrollRequest}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof enrollRoute>>,
        TError,
        {data: EnrollRequest},
        TContext
      > => {
      return useMutation(getEnrollRouteMutationOptions(options), queryClient);
    }
